import { createUserAccessActions } from '../admin/userAccessActions';
import { createDocumentActions } from '../documents/documentActions';
import { createPersonnelActions } from '../personnel/personnelActions';
import { createPricelistActions } from '../pricelists/pricelistActions';
import { createProjectOperationActions } from '../project-operations/projectOperationActions';
import { createProjectCrudActions } from '../projects/projectCrudActions';
import { createSupplyActions } from '../supply/supplyActions';
import { createSupplyPlanningUi } from '../supply/supplyPlanningUi';
import { createWarehouseCrudActions } from '../warehouse/warehouseCrudActions';
import { createWorkJournalActions } from '../work-journal/workJournalActions';

export function buildAppActionGroups({
  API,
  appMainState = {},
  businessRuntime = {},
  constants = {},
  coreRuntime = {},
  documentSelectors = {},
  estimateRuntime = {},
  shellOverlayState = {},
  supplyWorkflowState = {},
  ui = {},
  utilities = {},
  user
}) {
  const {
    CHECKLIST_TEMPLATES,
    EMPTY_ESTIMATE_CHANGE,
    GENERAL_WORK_ROOM_NAME,
    ROLE_LABELS
  } = constants;
  const {
    C,
    btnB,
    btnG
  } = ui;
  const {
    addActivity,

    isFinanceRole,
    loadChecklistItems,
    loadPricelistItems,
    navigateTo,
    notify,
    refreshData

  } = coreRuntime;
  const {
    documentActionRefs
  } = businessRuntime;
  const {
    createInvoiceControlReviewTasksForInvoice,
    getProjectWorkPackageOptions,
    isPersonalMaterialRole,
    materialNameKey

  } = businessRuntime;
  const {
    applyMaterialOverNormReason,
    autoFillNormMaterialsForWork,
    getRoomNetWall,
    ks2ItemsFromEstimate,
    materialNormControlSummaryForProject,
    materialNormOverrunReason,
    materialReconciliationRows,
    materialWriteoffBlockMessage,
    roomMeasurementCheck,
    roomMeasurementMessage,
    warehouseInvoiceEstimateControl,
    warehouseInvoiceItems
  } = businessRuntime;
  const {
    activeEstimatesForProject,
    estimateChangeRowsForDocs,
    estimateWorkNormRequirementRows,
    expByCategory,
    isSupplyDeliveryInvoice
  } = businessRuntime;
  const {
    estimatePackage,
    estimateWorkKey,
    fmtMeasure,
    isSameSupplyMaterial,

    readApiResult,
    supplyRequestOrigin,
    supplyUnitKey,
    toNum
  } = documentSelectors;
  const {
    calcDoorArea,
    calcDoorReveals,
    calcVat,
    calcWindowArea,
    calcWindowReveals,
    cableTypeOf,
    contractRequisitesWarning,
    denormalizeMeasure,
    generateQR
  } = utilities;
  const {
    estimateWorkMaterials,
    estimateWorkParams
  } = estimateRuntime;
  const {
    setShowReceiveDialog,
    setShowScanInvoice
  } = shellOverlayState;
  const {
    newOfferInvoice,
    newSupplyReq,
    receiveForm,
    selectedSupplierIds,
    setCompareLoadingReqId,
    setCompareResultByReq,
    setDeliveryAiLoadingId,
    setDeliveryAiResultById,
    setGeneratedInviteLink,
    setInvoicingOfferId,
    setNewOfferInvoice,
    setNewSupplyReq,
    setReceiveForm,
    setReceivingDeliveryId,
    setRequestKpLoading,
    setSelectedSupplierIds,
    setShipmentForm,
    setShippingOfferId,
    setShowRequestKpModal,
    setShowSupplyForm,
    setSuggestedSuppliers,
    setSupplyAiLoading,
    setSupplyAiText,
    setSupplyRejectId,
    setSupplyRejectReason,
    setSupplyStockCheck,
    shipmentForm,
    showRequestKpModal,
    suggestedSuppliers,
    supplierInviteForm,
    supplyRejectReason
  } = supplyWorkflowState;
  const {
    accountablePayments,
    actPayments,
    allBrigadeItems,
    brigadeContracts,
    cableJournal,
    companyName,
    companyReqForm,
    companyRequisites,
    contracts,
    customRoomTypes,
    draftRoomDoors,
    draftRoomWindows,
    editingItem,
    editingPlItem,
    expandedStaffId,
    hiddenActs,
    inlineEditPlData,
    inlineEditPrice,
    interimActs,
    issueToolData,
    masterProfiles,
    masterProjectId,
    masterRatings,
    materialInspections,
    materialTransfers,
    newAct,
    newChecklist,
    newClient,
    newContract,
    newDoor,
    newInvoice,
    newInviteRole,
    newMovement,
    newOffer,
    newPiecework,
    newPlItem,
    newPrescription,
    newPricelist,
    newProject,
    newRequest,
    newRoom,
    newStaff,
    newStaffDoc,
    newStage,
    newSupplier,
    newTask,
    newTool,
    newUnexpected,
    newUser,
    newWarehouse,
    newWeather,
    newWindow,
    ownExpenses,
    prescriptionsList,
    priceHints,
    pricelistItems,
    pricelists,
    projects,
    returnToolCondition,
    roomDoors,
    roomWindows,
    rooms,
    selectedPricelist,
    selectedWorks,
    sitePublicationDrafts,
    staff,
    supervisorActs,
    supplierInvoices,
    suppliers,
    supplyRequests,
    supplyTemplates,
    tbJournal,
    tools,
    users,
    weatherLog,
    workJournal,
    setActiveProjectTab,
    setActiveTabGroup,
    setConfirmAcceptedQty,
    setConfirmComment,
    setConfirmingEntry,
    setCustomRoomTypes,
    setDraftRoomDoors,
    setDraftRoomWindows,
    setEditingDoor,
    setEditingItem,
    setEditingPlItem,
    setEditingWindow,
    setEstimateDoneDrafts,
    setEstimateWorkMaterials,
    setEstimateWorkParams,
    setExpandedProject,
    setExpandedRoom,
    setExpandedStaffId,
    setInlineEditPl,
    setInlineEditPlData,
    setInlineEditPrice,
    setIssueToolData,
    setMasterProjectId,
    setMasterRatings,
    setNewAct,
    setNewChecklist,
    setNewClient,
    setNewContract,
    setNewDoor,
    setNewInvoice,
    setNewMovement,
    setNewOffer,
    setNewPiecework,
    setNewPlItem,
    setNewPrescription,
    setNewPricelist,
    setNewProject,
    setNewRequest,
    setNewRoom,
    setNewStaff,
    setNewStaffDoc,
    setNewStage,
    setNewSupplier,
    setNewTask,
    setNewTool,
    setNewUnexpected,
    setNewUser,
    setNewWarehouse,
    setNewWeather,
    setNewWindow,
    setPayrollExtras,
    setPriceHints,
    setPricelistItems,
    setRejectComment,
    setRejectingEntry,
    setReturnToolCondition,
    setRoomDoors,
    setRoomWindows,
    setSalaryEdits,
    setSalaryPayments,
    setSelectedPricelist,
    setSelectedWorks,
    setShowForm,
    setShowIssueToolModal,
    setShowReturnToolModal,
    setShowRoomForm,
    setShowStaffDocForm,
    setSitePublicationDrafts,
    setStaffProfile,
    setStaffProfileLoading,
    setTbJournal,
    setTimesheet,
    setWarehouseTab,
    setWeatherLog
  } = appMainState;

  const personnelActions = createPersonnelActions({
    API,
    ROLE_LABELS,
    contracts,
    editingItem,
    expandedStaffId,
    interimActs,
    masterProfiles,
    masterRatings,
    newAct,
    newContract,
    newPiecework,
    newStaff,
    newStaffDoc,
    notify,
    readApiResult,
    refreshData,
    setEditingItem,
    setExpandedStaffId,
    setNewAct,
    setNewContract,
    setNewPiecework,
    setNewStaff,
    setNewStaffDoc,
    setMasterRatings,
    setPayrollExtras,
    setSalaryPayments,
    setSalaryEdits,
    setShowForm,
    setShowStaffDocForm,
    setStaffProfile,
    setStaffProfileLoading,
    setTimesheet,
    projects,
    staff,
    user,
    users,
    workJournal
  });
  const { resolveContractPerformer } = personnelActions;

  const documentActions = createDocumentActions({
    accountablePayments,
    activeEstimatesForProject,
    actPayments,
    allBrigadeItems,
    calcDoorArea,
    calcDoorReveals,
    calcVat,
    calcWindowArea,
    calcWindowReveals,
    cableJournal,
    cableTypeOf,
    companyName,
    companyRequisites,
    contractRequisitesWarning,
    estimateChangeRowsForDocs,
    estimateWorkNormRequirementRows,
    expByCategory,
    generateQR,
    getRoomNetWall,
    hiddenActs,
    interimActs,
    isFinanceRole,
    isSupplyDeliveryInvoice,
    ks2ItemsFromEstimate,
    materialInspections,
    materialNormControlSummaryForProject,
    materialReconciliationRows,
    materialTransfers,
    masterProfiles,
    ownExpenses,
    prescriptionsList,
    projects,
    resolveContractPerformer,
    roomDoors,
    rooms,
    roomWindows,
    showPreview: utilities.showPreview,
    supervisorActs,
    supplierInvoices,
    tbJournal,
    tools,
    user,
    users,
    warehouseInvoiceEstimateControl,
    warehouseInvoiceItems,
    weatherLog,
    workJournal
  });
  const {
    buildMaterialRequirementContent
  } = documentActions;
  if (documentActionRefs) {
    documentActionRefs.buildMaterialRequirementContent = buildMaterialRequirementContent;
  }

  const projectCrudActions = createProjectCrudActions({
    API,
    brigadeContracts,
    editingItem,
    newClient,
    newProject,
    newTask,
    notify,
    projects,
    readApiResult,
    refreshData,
    setEditingItem,
    setNewClient,
    setNewProject,
    setNewTask,
    setShowForm,
    setSitePublicationDrafts,
    sitePublicationDrafts,
    addActivity
  });

  const warehouseActions = createWarehouseCrudActions({
    API,
    addActivity,
    calcVat,
    createInvoiceControlReviewTasksForInvoice,
    editingItem,
    getProjectWorkPackageOptions,
    issueToolData,
    newInvoice,
    newMovement,
    newTool,
    notify,
    projects,
    refreshData,
    returnToolCondition,
    setEditingItem,
    setIssueToolData,
    setNewInvoice,
    setNewMovement,
    setNewTool,
    setReturnToolCondition,
    setShowReceiveDialog,
    setShowForm,
    setShowIssueToolModal,
    setShowReturnToolModal,
    setShowScanInvoice,
    suppliers,
    user
  });

  const workJournalActions = createWorkJournalActions({
    API,
    GENERAL_WORK_ROOM_NAME,
    addActivity,
    applyMaterialOverNormReason,
    autoFillNormMaterialsForWork,
    denormalizeMeasure,
    estimatePackage,
    estimateWorkKey,
    estimateWorkMaterials,
    estimateWorkParams,
    fmtMeasure,
    isFinanceRole,
    isPersonalMaterialRole,
    materialNameKey,
    materialNormOverrunReason,
    materialWriteoffBlockMessage,
    masterProjectId,
    notify,
    pricelistItems,
    pricelists,
    projects,
    refreshData,
    roomMeasurementCheck,
    roomMeasurementMessage,
    rooms,
    selectedWorks,
    setConfirmAcceptedQty,
    setConfirmComment,
    setConfirmingEntry,
    setEstimateDoneDrafts,
    setEstimateWorkMaterials,
    setEstimateWorkParams,
    setEstimatesList: appMainState.setEstimatesList,
    setMasterProjectId,
    setPricelistItems,
    setRejectComment,
    setRejectingEntry,
    setSelectedWorks,
    toNum,
    updateProjectProgress: projectCrudActions.updateProjectProgress,
    user
  });

  const userAccessActions = createUserAccessActions({
    API,
    editingItem,
    newInviteRole,
    newUser,
    refreshData,
    setEditingItem,
    setGeneratedInviteLink,
    setNewUser,
    setShowForm,
    supplierInviteForm,
    suppliers,
    user
  });

  const pricelistActions = createPricelistActions({
    API,
    editingItem,
    editingPlItem,
    inlineEditPlData,
    inlineEditPrice,
    loadPricelistItems,
    newPlItem,
    newPricelist,
    refreshData,
    selectedPricelist,
    setEditingItem,
    setEditingPlItem,
    setInlineEditPl,
    setInlineEditPlData,
    setInlineEditPrice,
    setNewPlItem,
    setNewPricelist,
    setPricelistItems,
    setSelectedPricelist,
    setShowForm
  });

  const supplyActions = createSupplyActions({
    API,
    editingItem,
    getProjectWorkPackageOptions,
    newOffer,
    newOfferInvoice,
    newRequest,
    newSupplier,
    newSupplyReq,
    notify,
    priceHints,
    receiveForm,
    refreshData,
    selectedSupplierIds,
    setCompareLoadingReqId,
    setCompareResultByReq,
    setDeliveryAiLoadingId,
    setDeliveryAiResultById,
    setEditingItem,
    setInvoicingOfferId,
    setNewOffer,
    setNewOfferInvoice,
    setNewRequest,
    setNewSupplier,
    setNewSupplyReq,
    setPriceHints,
    setReceiveForm,
    setReceivingDeliveryId,
    setRequestKpLoading,
    setSelectedSupplierIds,
    setShipmentForm,
    setShippingOfferId,
    setShowForm,
    setShowRequestKpModal,
    setShowSupplyForm,
    setSuggestedSuppliers,
    setSupplyAiLoading,
    setSupplyAiText,
    setSupplyRejectId,
    setSupplyRejectReason,
    setSupplyStockCheck,
    shipmentForm,
    showRequestKpModal,
    suggestedSuppliers,
    supplyRejectReason,
    supplyRequests,
    supplyTemplates,
    user
  });

  const projectOperationActions = createProjectOperationActions({
    API,
    CHECKLIST_TEMPLATES,
    EMPTY_ESTIMATE_CHANGE,
    companyReqForm,
    customRoomTypes,
    draftRoomDoors,
    draftRoomWindows,
    editingItem,
    loadChecklistItems,
    newChecklist,
    newDoor,
    newPrescription,
    newRoom,
    newStage,
    newUnexpected,
    newWarehouse,
    newWeather,
    newWindow,
    notify,
    refreshData,
    roomDoors,
    roomWindows,
    setCustomRoomTypes,
    setDraftRoomDoors,
    setDraftRoomWindows,
    setEditingDoor,
    setEditingItem,
    setEditingWindow,
    setExpandedRoom,
    setNewChecklist,
    setNewDoor,
    setNewPrescription,
    setNewRoom,
    setNewStage,
    setNewUnexpected,
    setNewWarehouse,
    setNewWeather,
    setNewWindow,
    setRoomDoors,
    setRoomWindows,
    setShowForm,
    setShowRoomForm,
    setTbJournal,
    setWeatherLog,
    tbJournal,
    toNum,
    user,
    weatherLog
  });

  const supplyPlanningUi = createSupplyPlanningUi({
    C,
    btnB,
    btnG,
    projects,
    user,
    navigateTo,
    setExpandedProject,
    setActiveProjectTab,
    setActiveTabGroup,
    setWarehouseTab,
    supplyRequestOrigin,
    newSupplyReq,
    setNewSupplyReq,
    materialReconciliationRows,
    canonicalMaterialMeta: businessRuntime.canonicalMaterialMeta,
    isSameSupplyMaterial,
    supplyUnitKey,
    toNum,
    fmtMeasure
  });

  return {
    documentActions,
    personnelActions,
    pricelistActions,
    projectCrudActions,
    projectOperationActions,
    supplyActions,
    supplyPlanningUi,
    userAccessActions,
    warehouseActions,
    workJournalActions
  };
}
