export const createProjectForm = (overrides = {}) => ({
  name: '',
  clientId: null,
  client: '',
  status: 'Планирование',
  budget: '',
  deadline: '',
  progress: 0,
  tasks: [],
  pricelistId: null,
  ...overrides,
});

export const createClientForm = (overrides = {}) => ({
  name: '',
  phone: '',
  email: '',
  status: 'Активный',
  notes: '',
  inn: '',
  kpp: '',
  ogrn: '',
  legalAddress: '',
  actualAddress: '',
  directorName: '',
  directorPosition: '',
  basis: '',
  bankName: '',
  bik: '',
  rs: '',
  ks: '',
  ...overrides,
});
