const directorMapMockContract = {
  contractVersion: 'director-map.v1',
  mode: 'sandbox_unbound',
  integrationPolicy: {
    readOnly: true,
    writesToAccounting: false,
    writesToWarehouse: false,
    writesToWorkJournal: false,
    autoScheduleShift: false,
    autoLinkThreshold: 90,
    uncertainState: 'needs_review',
  },
  project: {
    id: 'mock-project-1',
    name: 'Лермонтова, спортзал',
    status: 'В работе',
    deadline: '2026-08-15',
    directorViewTitle: 'Карта руководителя',
  },
  summary: {
    plannedProgress: 76,
    factProgress: 62,
    lagPercent: 14,
    redSignals: 2,
    yellowSignals: 5,
    reviewItems: 5,
    moneyFact: 1850000,
    moneyObligations: 420000,
  },
  items: [
    {
      id: 'work-node-demolition',
      type: 'work_node',
      title: 'Демонтаж и вывоз',
      workPackage: 'Демонтаж',
      zone: 'Зал 1, коридор',
      status: 'Завершен',
      priority: 'normal',
      responsible: 'Прораб Иванов',
      startDate: '2026-06-01',
      endDate: '2026-06-10',
      plannedProgress: 100,
      factProgress: 100,
      reviewState: 'ok',
      money: { plan: 310000, fact: 310000, obligations: 0, factSourceRule: 'project_payments_only' },
      timeline: { startPercent: 0, widthPercent: 18 },
      sourceRefs: {
        stage: { status: 'mock', label: 'этап закрыт', futureSource: 'project_stages' },
        estimate: { status: 'mock', label: 'смета: Демонтаж', futureSource: 'estimates' },
        workJournal: { status: 'mock', label: 'ЖПР 12/12', futureSource: 'work_journal' },
        payments: { status: 'mock', label: '310 000 ₽ факт', futureSource: 'project_payments' },
      },
      signals: [],
      supplyChain: [],
    },
    {
      id: 'work-node-screed',
      type: 'work_node',
      title: 'Стяжка и подготовка основания',
      workPackage: 'Полы',
      zone: 'Зал 1',
      status: 'В работе',
      priority: 'high',
      responsible: 'Прораб Иванов',
      startDate: '2026-06-20',
      endDate: '2026-07-04',
      plannedProgress: 74,
      factProgress: 54,
      reviewState: 'needs_review',
      money: { plan: 820000, fact: 410000, obligations: 148000, factSourceRule: 'project_payments_only' },
      timeline: { startPercent: 17, widthPercent: 24 },
      sourceRefs: {
        stage: { status: 'mock', label: 'в работе', futureSource: 'project_stages' },
        estimate: { status: 'mock', label: 'смета: Полы', futureSource: 'estimates' },
        workJournal: { status: 'needs_review', label: '2 ЖПР без зоны', futureSource: 'work_journal' },
        supply: { status: 'mock', label: 'поставка частичная', futureSource: 'supply_requests/supply_deliveries' },
        warehouse: { status: 'mock', label: '80 м2 на объекте', futureSource: 'warehouse_invoices/materials' },
        documents: { status: 'warning', label: 'сертификат нужен', futureSource: 'material_inspection_journal' },
        payments: { status: 'mock', label: '410 000 ₽ факт', futureSource: 'project_payments' },
      },
      signals: [
        {
          id: 'sig-screed-material',
          type: 'material',
          severity: 'red',
          title: 'Не хватает армирующей сетки 120 м2',
          explanation: 'Поставка принята частично, объем не закрывает текущую потребность этапа.',
          nextAction: { type: 'open_source', label: 'Открыть поставку', enabledInSandbox: false },
        },
        {
          id: 'sig-screed-room',
          type: 'link_quality',
          severity: 'yellow',
          title: 'Две записи ЖПР без помещения',
          explanation: 'Факт есть, но связь с зоной требует проверки прорабом.',
          nextAction: { type: 'review_link', label: 'Проверить связь', enabledInSandbox: false },
        },
      ],
      supplyChain: [
        { step: 'need', title: 'Потребность', status: 'info', value: '120 м2 не хватает', description: 'Из сметы и текущего этапа.' },
        { step: 'request', title: 'Заявка', status: 'ok', value: 'Заявка #55', description: 'Согласована директором.' },
        { step: 'offer', title: 'КП', status: 'ok', value: 'Поставщик выбран', description: 'Цена и срок согласованы.' },
        { step: 'invoice', title: 'Счет', status: 'warning', value: 'Оплата частичная', description: 'Факт только из платежей проекта.' },
        { step: 'shipment', title: 'Отгрузка', status: 'danger', value: '80 из 200 м2', description: 'Нужен дозавоз.' },
        { step: 'acceptance', title: 'Приемка', status: 'danger', value: 'Недостача 120 м2', description: 'Можно открыть претензию.' },
        { step: 'primary_document', title: 'Накладная', status: 'warning', value: 'Фото загружено', description: 'Бухгалтерия проверяет сумму.' },
        { step: 'quality_control', title: 'Входной контроль', status: 'warning', value: 'Нет сертификата', description: 'Контроль качества не закрыт.' },
        { step: 'warehouse', title: 'Склад', status: 'info', value: '80 м2 на объекте', description: 'Выдача мастеру не оформлена.' },
        { step: 'work_journal', title: 'ЖПР', status: 'info', value: 'Списание после работы', description: 'Факт появится после выдачи.' },
      ],
    },
    {
      id: 'work-node-electric',
      type: 'work_node',
      title: 'Электрика под скрытые работы',
      workPackage: 'Электрика',
      zone: 'Зал 1, серверная',
      status: 'В работе',
      priority: 'high',
      responsible: 'Главный инженер',
      startDate: '2026-06-28',
      endDate: '2026-07-12',
      plannedProgress: 68,
      factProgress: 48,
      reviewState: 'needs_review',
      money: { plan: 540000, fact: 260000, obligations: 90000, factSourceRule: 'project_payments_only' },
      timeline: { startPercent: 34, widthPercent: 26 },
      sourceRefs: {
        stage: { status: 'mock', label: 'в работе', futureSource: 'project_stages' },
        estimate: { status: 'mock', label: 'смета: Электрика', futureSource: 'estimates' },
        workJournal: { status: 'mock', label: 'ЖПР 5', futureSource: 'work_journal' },
        documents: { status: 'needs_review', label: 'АОСР не создан', futureSource: 'hidden_works_acts' },
        payments: { status: 'mock', label: '260 000 ₽ факт', futureSource: 'project_payments' },
      },
      signals: [
        {
          id: 'sig-electric-act',
          type: 'document',
          severity: 'red',
          title: 'Скрытые работы есть, АОСР еще не создан',
          explanation: 'До закрытия штроб нужен акт и фотофиксация.',
          nextAction: { type: 'open_source', label: 'Открыть АОСР', enabledInSandbox: false },
        },
        {
          id: 'sig-electric-photo',
          type: 'document',
          severity: 'yellow',
          title: 'Нужна фотофиксация до закрытия',
          explanation: 'Документальный риск, но без жесткого стопа.',
          nextAction: { type: 'create_task', label: 'Создать задачу', enabledInSandbox: false },
        },
      ],
      supplyChain: [],
    },
    {
      id: 'work-node-walls',
      type: 'work_node',
      title: 'Штукатурка и стены',
      workPackage: 'Отделка',
      zone: 'Зал 1',
      status: 'Не начат',
      priority: 'normal',
      responsible: 'Мастер Петров',
      startDate: '2026-07-08',
      endDate: '2026-07-20',
      plannedProgress: 24,
      factProgress: 0,
      reviewState: 'needs_review',
      money: { plan: 460000, fact: 0, obligations: 74000, factSourceRule: 'project_payments_only' },
      timeline: { startPercent: 56, widthPercent: 22 },
      sourceRefs: {
        stage: { status: 'mock', label: 'ожидает', futureSource: 'project_stages' },
        estimate: { status: 'mock', label: 'смета: Отделка', futureSource: 'estimates' },
        supply: { status: 'warning', label: 'выдачи нет', futureSource: 'supply_requests/materials' },
        documents: { status: 'needs_review', label: 'зависит от АОСР', futureSource: 'hidden_works_acts' },
      },
      signals: [
        {
          id: 'sig-walls-dependency',
          type: 'document',
          severity: 'yellow',
          title: 'Старт зависит от АОСР по электрике',
          explanation: 'Зависимость показываем как сигнал, даты автоматически не переносим.',
          nextAction: { type: 'review_link', label: 'Проверить зависимость', enabledInSandbox: false },
        },
        {
          id: 'sig-walls-issue',
          type: 'material',
          severity: 'yellow',
          title: 'Материал зарезервирован, выдачи на объект нет',
          explanation: 'Склад и ЖПР не проводятся из карты.',
          nextAction: { type: 'open_source', label: 'Открыть склад', enabledInSandbox: false },
        },
      ],
      supplyChain: [],
    },
    {
      id: 'work-node-flooring',
      type: 'work_node',
      title: 'Финишное покрытие пола',
      workPackage: 'Полы',
      zone: 'Зал 1',
      status: 'Следующий',
      priority: 'normal',
      responsible: 'Субподрядчик СК Пол',
      startDate: '2026-07-21',
      endDate: '2026-08-01',
      plannedProgress: 0,
      factProgress: 0,
      reviewState: 'needs_review',
      money: { plan: 680000, fact: 0, obligations: 108000, factSourceRule: 'project_payments_only' },
      timeline: { startPercent: 76, widthPercent: 18 },
      sourceRefs: {
        stage: { status: 'mock', label: 'следующий', futureSource: 'project_stages' },
        estimate: { status: 'mock', label: 'смета: Покрытие', futureSource: 'estimates' },
        payments: { status: 'warning', label: 'счет на проверке', futureSource: 'supplier_invoices/project_payments' },
      },
      signals: [
        {
          id: 'sig-flooring-money',
          type: 'money',
          severity: 'yellow',
          title: 'Счет есть, фактической оплаты еще нет',
          explanation: 'Обязательство видно, но факт появится только через project_payments.',
          nextAction: { type: 'open_source', label: 'Открыть счет', enabledInSandbox: false },
        },
      ],
      supplyChain: [],
    },
  ],
  unlinked: {
    workJournal: [],
    materials: [],
    documents: [],
    payments: [],
  },
  guards: [
    'no_fact_money_outside_project_payments',
    'no_warehouse_changes_from_director_map',
    'no_work_journal_confirmation_from_director_map',
    'no_auto_date_shift',
    'all_low_confidence_links_go_to_needs_review',
  ],
};

export default directorMapMockContract;
