export const buildLeadPayload = (lead = {}, { createdBy = '', createdAt = '', includeCreateMeta = false } = {}) => {
  const body = {
    name: lead.name || '',
    phone: lead.phone || '',
    email: lead.email || '',
    source: lead.source || '',
    budget: Number(lead.budget) || 0,
    notes: lead.notes || '',
    stage: lead.stage || 'Новый',
    photoUrl: lead.photoUrl || '',
    leadType: lead.leadType || 'Клиент',
    counterpartyType: lead.counterpartyType || '',
    responsibleName: lead.responsibleName || '',
    nextContactAt: lead.nextContactAt || '',
    address: lead.address || '',
    workType: lead.workType || '',
    area: Number(lead.area) || 0,
    priority: lead.priority || 'Обычный',
    lossReason: lead.lossReason || '',
    legalForm: lead.legalForm || '',
    passportData: lead.passportData || '',
    inn: lead.inn || '',
    kpp: lead.kpp || '',
    ogrn: lead.ogrn || '',
    legalAddress: lead.legalAddress || '',
    contractSubject: lead.contractSubject || '',
    bank: lead.bank || '',
    bik: lead.bik || '',
    bankAccount: lead.bankAccount || '',
    corrAccount: lead.corrAccount || '',
    signerName: lead.signerName || '',
    signerBasis: lead.signerBasis || '',
    estimateId: Number(lead.estimateId) || null,
    documentStatus: lead.documentStatus || 'Не собраны',
    reviewStatus: lead.reviewStatus || 'Новая',
  };

  return includeCreateMeta ? { ...body, createdBy, createdAt } : body;
};
