import React from 'react';
import AccountingTabsNav from './AccountingTabsNav';
import AccountingSummaryPanel from './AccountingSummaryPanel';
import AccountingPaymentsPanel from './AccountingPaymentsPanel';
import AccountingExpenseReportsPanel from './AccountingExpenseReportsPanel';
import AccountingAuditPanel from './AccountingAuditPanel';
import AccountingDocumentsPanel from './AccountingDocumentsPanel';
import AccountingIncomingDocumentsPanel from './AccountingIncomingDocumentsPanel';
import AccountingSupplierDocumentsPanel from './AccountingSupplierDocumentsPanel';
import AccountingSalaryPanel from './AccountingSalaryPanel';
import AccountingActsPanel from './AccountingActsPanel';
import AccountingContractsPanel from './AccountingContractsPanel';
import AccountingPerformerClosingPanel from './AccountingPerformerClosingPanel';

export default function AccountingPage(props) {
  const {
    accountingTab,
    setAccountingTab,
    setShowForm,
    isLeadership,
    loadAuditLog,
    btnO,
    btnG,
    C,
    card,
    projects,
    estimatesList,
    projectPayments,
    projectPaymentInAmount,
    ownExpenses,
    manualExpenses,
    accountablePayments,
    supplierInvoices,
    brigadeContracts,
    piecework,
    isFinanceRole,
    inp,
    btnGr,
    matchSearch,
    listSearch,
    setListSearch,
    toNum,
    user,
    refreshData,
    setShowReimburseModal,
    interimActs,
    expandedProject,
    setExpandedProject,
    btnB,
    btnR,
    badge,
    showForm,
    newContract,
    setNewContract,
    resolveContractPerformer,
    contractRequisitesWarning,
    createContract,
    staff,
    contracts,
    projectDocuments,
    normalizePersonKey,
    allBrigadePayments,
    pdConsents,
    allBrigadeItems,
    showPreview,
    buildContractContent,
    deleteContract,
    workJournal,
    unexpectedWorksList,
    isApprovedEstimateChangeStatus,
    expandedActDate,
    setExpandedActDate,
    fmtMeasure,
    newAct,
    setNewAct,
    masterProfiles,
    createInterimAct,
    buildActContent,
    fileSrc,
    uploadPhoto,
    setShowPhotoModal,
    setShowPayActModal,
    deleteInterimAct,
    buildBrigadeActContent,
    accountingDocProject,
    setAccountingDocProject,
    projectPlanDone,
    materialControlSummaryForProject,
    invoices,
    warehouseInvoiceEstimateControl,
    buildPassportContent,
    showKS2,
    buildKS3Content,
    buildJPRContent,
    buildM29Content,
    buildAOSKContent,
    buildKS11Content,
    buildKS14Content,
    buildIGDContent,
    buildExecPackageContent,
    buildVATBookContent,
    buildInvoiceContent,
    suppliers,
    buildM2Content,
    buildM8Content,
    buildMaterialRequirementContent,
    buildSpecJournalContent,
    salaryMonth,
    setSalaryMonth,
    salaryEdits,
    payrollExtras,
    tools,
    setSalaryEdit,
    salaryPayments,
    setSalaryPayments,
    paySalary,
    setPayrollExtra,
    newExpenseReport,
    setNewExpenseReport,
    expenseReports,
    auditLog,
    setAuditLog,
    tbl,
    tblH,
    tblC,
    isMobile,
  } = props;

  return (
    <div>
      <AccountingTabsNav
        accountingTab={accountingTab}
        setAccountingTab={setAccountingTab}
        setShowForm={setShowForm}
        isLeadership={isLeadership}
        loadAuditLog={loadAuditLog}
        btnO={btnO}
        btnG={btnG}
      />

      {accountingTab === 'summary' && (
        <AccountingSummaryPanel
          C={C}
          card={card}
          projects={projects}
          projectPayments={projectPayments}
          projectPaymentInAmount={projectPaymentInAmount}
          ownExpenses={ownExpenses}
          manualExpenses={manualExpenses}
          accountablePayments={accountablePayments}
          supplierInvoices={supplierInvoices}
          brigadeContracts={brigadeContracts}
          piecework={piecework}
          isLeadership={isLeadership}
          invoices={invoices}
          warehouseInvoiceEstimateControl={warehouseInvoiceEstimateControl}
          setAccountingTab={setAccountingTab}
        />
      )}

      {accountingTab === 'incoming' && (
        <AccountingIncomingDocumentsPanel
          C={C}
          card={card}
          btnO={btnO}
          btnG={btnG}
          btnB={btnB}
          btnR={btnR}
          btnGr={btnGr}
          inp={inp}
          invoices={invoices}
          supplierInvoices={supplierInvoices}
          warehouseInvoiceEstimateControl={warehouseInvoiceEstimateControl}
          fileSrc={fileSrc}
          setShowPhotoModal={setShowPhotoModal}
          showPreview={showPreview}
          buildInvoiceContent={buildInvoiceContent}
          uploadPhoto={uploadPhoto}
          refreshData={refreshData}
          badge={badge}
          toNum={toNum}
        />
      )}

      {accountingTab === 'supplierDocs' && (
        <AccountingSupplierDocumentsPanel
          C={C}
          card={card}
          btnG={btnG}
          btnB={btnB}
          inp={inp}
          invoices={invoices}
          supplierInvoices={supplierInvoices}
          suppliers={suppliers}
          warehouseInvoiceEstimateControl={warehouseInvoiceEstimateControl}
          fileSrc={fileSrc}
          setShowPhotoModal={setShowPhotoModal}
          refreshData={refreshData}
          matchSearch={matchSearch}
          listSearch={listSearch}
          setListSearch={setListSearch}
        />
      )}

      {accountingTab === 'payments' && (
        <AccountingPaymentsPanel
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          btnGr={btnGr}
          matchSearch={matchSearch}
          listSearch={listSearch}
          setListSearch={setListSearch}
          projects={projects}
          toNum={toNum}
          user={user}
          refreshData={refreshData}
          setShowReimburseModal={setShowReimburseModal}
          ownExpenses={ownExpenses}
          manualExpenses={manualExpenses}
          projectPayments={projectPayments}
          projectPaymentInAmount={projectPaymentInAmount}
          accountablePayments={accountablePayments}
          supplierInvoices={supplierInvoices}
          interimActs={interimActs}
          expandedProject={expandedProject}
          setExpandedProject={setExpandedProject}
        />
      )}

      {accountingTab === 'contracts' && (
        <AccountingContractsPanel
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          btnB={btnB}
          btnR={btnR}
          badge={badge}
          isFinanceRole={isFinanceRole}
          showForm={showForm}
          setShowForm={setShowForm}
          newContract={newContract}
          setNewContract={setNewContract}
          resolveContractPerformer={resolveContractPerformer}
          contractRequisitesWarning={contractRequisitesWarning}
          createContract={createContract}
          projects={projects}
          staff={staff}
          listSearch={listSearch}
          setListSearch={setListSearch}
          matchSearch={matchSearch}
          contracts={contracts}
          brigadeContracts={brigadeContracts}
          projectDocuments={projectDocuments}
          normalizePersonKey={normalizePersonKey}
          allBrigadePayments={allBrigadePayments}
          interimActs={interimActs}
          pdConsents={pdConsents}
          allBrigadeItems={allBrigadeItems}
          showPreview={showPreview}
          buildContractContent={buildContractContent}
          deleteContract={deleteContract}
        />
      )}

      {accountingTab === 'acts' && (
        <AccountingActsPanel
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          btnB={btnB}
          btnR={btnR}
          badge={badge}
          listSearch={listSearch}
          setListSearch={setListSearch}
          matchSearch={matchSearch}
          workJournal={workJournal}
          unexpectedWorksList={unexpectedWorksList}
          isApprovedEstimateChangeStatus={isApprovedEstimateChangeStatus}
          expandedProject={expandedProject}
          setExpandedProject={setExpandedProject}
          expandedActDate={expandedActDate}
          setExpandedActDate={setExpandedActDate}
          fmtMeasure={fmtMeasure}
          showForm={showForm}
          setShowForm={setShowForm}
          isFinanceRole={isFinanceRole}
          newAct={newAct}
          setNewAct={setNewAct}
          masterProfiles={masterProfiles}
          staff={staff}
          projects={projects}
          estimatesList={estimatesList}
          createInterimAct={createInterimAct}
          interimActs={interimActs}
          showPreview={showPreview}
          buildActContent={buildActContent}
          fileSrc={fileSrc}
          uploadPhoto={uploadPhoto}
          refreshData={refreshData}
          setShowPayActModal={setShowPayActModal}
          deleteInterimAct={deleteInterimAct}
          brigadeContracts={brigadeContracts}
          buildBrigadeActContent={buildBrigadeActContent}
        />
      )}

      {accountingTab === 'performerClosing' && (
        <AccountingPerformerClosingPanel
          C={C}
          card={card}
          inp={inp}
          btnG={btnG}
          btnB={btnB}
          tbl={tbl}
          tblH={tblH}
          tblC={tblC}
          workJournal={workJournal}
          staff={staff}
          accountablePayments={accountablePayments}
          ownExpenses={ownExpenses}
          projects={projects}
          listSearch={listSearch}
          setListSearch={setListSearch}
          matchSearch={matchSearch}
          showPreview={showPreview}
          interimActs={interimActs}
          contracts={contracts}
          refreshData={refreshData}
          btnO={btnO}
          projectPayments={projectPayments}
          user={user}
        />
      )}

      {accountingTab === 'documents' && (
        <AccountingDocumentsPanel
          C={C}
          card={card}
          btnO={btnO}
          btnG={btnG}
          btnB={btnB}
          accountingDocProject={accountingDocProject}
          setAccountingDocProject={setAccountingDocProject}
          projects={projects}
          projectPayments={projectPayments}
          manualExpenses={manualExpenses}
          projectPlanDone={projectPlanDone}
          ownExpenses={ownExpenses}
          accountablePayments={accountablePayments}
          supplierInvoices={supplierInvoices}
          brigadeContracts={brigadeContracts}
          materialControlSummaryForProject={materialControlSummaryForProject}
          invoices={invoices}
          warehouseInvoiceEstimateControl={warehouseInvoiceEstimateControl}
          badge={badge}
          showPreview={showPreview}
          buildPassportContent={buildPassportContent}
          showKS2={showKS2}
          buildKS3Content={buildKS3Content}
          buildJPRContent={buildJPRContent}
          buildM29Content={buildM29Content}
          buildAOSKContent={buildAOSKContent}
          buildKS11Content={buildKS11Content}
          buildKS14Content={buildKS14Content}
          buildIGDContent={buildIGDContent}
          buildExecPackageContent={buildExecPackageContent}
          buildVATBookContent={buildVATBookContent}
          suppliers={suppliers}
          buildM2Content={buildM2Content}
          buildM8Content={buildM8Content}
          buildMaterialRequirementContent={buildMaterialRequirementContent}
          buildSpecJournalContent={buildSpecJournalContent}
          interimActs={interimActs}
          buildActContent={buildActContent}
        />
      )}

      {accountingTab === 'salary' && (
        <AccountingSalaryPanel
          C={C}
          card={card}
          inp={inp}
          btnG={btnG}
          btnO={btnO}
          btnR={btnR}
          tbl={tbl}
          tblH={tblH}
          tblC={tblC}
          salaryMonth={salaryMonth}
          setSalaryMonth={setSalaryMonth}
          listSearch={listSearch}
          setListSearch={setListSearch}
          salaryEdits={salaryEdits}
          payrollExtras={payrollExtras}
          piecework={piecework}
          tools={tools}
          staff={staff}
          matchSearch={matchSearch}
          setSalaryEdit={setSalaryEdit}
          toNum={toNum}
          salaryPayments={salaryPayments}
          setSalaryPayments={setSalaryPayments}
          paySalary={paySalary}
          setPayrollExtra={setPayrollExtra}
        />
      )}

      {accountingTab === 'expenses' && (
        <AccountingExpenseReportsPanel
          isMobile={isMobile}
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          btnR={btnR}
          staff={staff}
          projects={projects}
          newExpenseReport={newExpenseReport}
          setNewExpenseReport={setNewExpenseReport}
          refreshData={refreshData}
          expenseReports={expenseReports}
          user={user}
          badge={badge}
        />
      )}

      {accountingTab === 'audit' && (
        <AccountingAuditPanel
          C={C}
          card={card}
          btnB={btnB}
          auditLog={auditLog}
          setAuditLog={setAuditLog}
          tbl={tbl}
          tblH={tblH}
          tblC={tblC}
        />
      )}
    </div>
  );
}
