import React from 'react';
import {
  AccountingPage,
  PersonnelPage,
} from '../app/lazyComponents';

export default function AppBackofficePages({ activePage, ui, constants, state, actions }) {
  const { API, C, badge, btnB, btnG, btnGr, btnO, btnR, card, inp, isMobile, tbl, tblC, tblH } = ui;
  const { PD_CONSENT_TEXT, ROLE_GROUPS, ROLE_LABELS, UNITS } = constants;
  const {
    accountablePayments,
    accountingDocProject,
    accountingTab,
    allBrigadeItems,
    allBrigadePayments,
    auditLog,
    brigadeContracts,
    contracts,
    editingItem,
    estimatesList,
    expandedActDate,
    expandedMaster,
    expandedMasterProject,
    expandedPieceworkProject,
    expandedProject,
    expandedStaffId,
    expenseReports,
    fileSrc,
    interimActs,
    invoices,
    listSearch,
    manualExpenses,
    masterProfiles,
    masterRatings,
    newAct,
    newContract,
    newExpenseReport,
    newPiecework,
    newStaff,
    newStaffDoc,
    ownExpenses,
    payrollExtras,
    pdConsents,
    personnelTab,
    piecework,
    projectDocuments,
    projectPaymentInAmount,
    projectPayments,
    projectPlanDone,
    projects,
    salaryEdits,
    salaryMonth,
    salaryPayments,
    showForm,
    showPiecework,
    showStaffDocForm,
    staff,
    staffExpandedSections,
    staffProfile,
    staffProfileLoading,
    supplierInvoices,
    suppliers,
    timesheet,
    tools,
    unexpectedWorksList,
    user,
    users,
    workJournal,
  } = state;
  const {
    addPiecework,
    addStaffDoc,
    buildAOSKContent,
    buildActContent,
    buildBrigadeActContent,
    buildContractContent,
    buildExecPackageContent,
    buildIGDContent,
    buildInvoiceContent,
    buildJPRContent,
    buildKS11Content,
    buildKS14Content,
    buildKS3Content,
    buildM29Content,
    buildM2Content,
    buildM8Content,
    buildMaterialRequirementContent,
    buildPassportContent,
    buildPositionInstructionContent,
    buildSpecJournalContent,
    buildVATBookContent,
    calcSalary,
    contractRequisitesWarning,
    createContract,
    createInterimAct,
    createStaffAccessFromPrompt,
    daysInMonth,
    deleteContract,
    deleteInterimAct,
    deletePiecework,
    deleteStaff,
    findUserForStaff,
    fmtMeasure,
    isApprovedEstimateChangeStatus,
    isFinanceRole,
    isLeadership,
    loadAuditLog,
    matchSearch,
    materialControlSummaryForProject,
    normalizePersonKey,
    openStaffProfile,
    paySalary,
    ratemaster,
    refreshData,
    resetStaffAccessPassword,
    resolveContractPerformer,
    roleColor,
    saveStaff,
    setAccountingDocProject,
    setAccountingTab,
    setAuditLog,
    setEditingItem,
    setExpandedActDate,
    setExpandedMaster,
    setExpandedMasterProject,
    setExpandedPieceworkProject,
    setExpandedProject,
    setListSearch,
    setNewAct,
    setNewContract,
    setNewExpenseReport,
    setNewPiecework,
    setNewStaff,
    setNewStaffDoc,
    setPayrollExtra,
    setPersonnelTab,
    setSalaryEdit,
    setSalaryMonth,
    setSalaryPayments,
    setShowForm,
    setShowPayActModal,
    setShowPhotoModal,
    setShowPiecework,
    setShowReimburseModal,
    setShowStaffDocForm,
    setStaffExpandedSections,
    setStaffProfile,
    showKS2,
    showPreview,
    toggleDay,
    toNum,
    uploadPhoto,
    warehouseInvoiceEstimateControl,
    workedDays,
  } = actions;
  const isLeadershipUser = typeof isLeadership === 'function' ? isLeadership() : Boolean(isLeadership);

  return (
    <>
      {activePage === 'accounting' && (
        <AccountingPage
          isMobile={isMobile}
          accountingTab={accountingTab}
          setAccountingTab={setAccountingTab}
          setShowForm={setShowForm}
          isLeadership={isLeadershipUser}
          loadAuditLog={loadAuditLog}
          btnO={btnO}
          btnG={btnG}
          C={C}
          card={card}
          projects={projects}
          projectPayments={projectPayments}
          projectPaymentInAmount={projectPaymentInAmount}
          ownExpenses={ownExpenses}
          manualExpenses={manualExpenses}
          accountablePayments={accountablePayments}
          supplierInvoices={supplierInvoices}
          brigadeContracts={brigadeContracts}
          piecework={piecework}
          isFinanceRole={isFinanceRole}
          inp={inp}
          btnGr={btnGr}
          matchSearch={matchSearch}
          listSearch={listSearch}
          setListSearch={setListSearch}
          toNum={toNum}
          user={user}
          refreshData={refreshData}
          setShowReimburseModal={setShowReimburseModal}
          interimActs={interimActs}
          expandedProject={expandedProject}
          setExpandedProject={setExpandedProject}
          btnB={btnB}
          btnR={btnR}
          badge={badge}
          showForm={showForm}
          newContract={newContract}
          setNewContract={setNewContract}
          resolveContractPerformer={resolveContractPerformer}
          contractRequisitesWarning={contractRequisitesWarning}
          createContract={createContract}
          staff={staff}
          contracts={contracts}
          projectDocuments={projectDocuments}
          normalizePersonKey={normalizePersonKey}
          allBrigadePayments={allBrigadePayments}
          pdConsents={pdConsents}
          allBrigadeItems={allBrigadeItems}
          showPreview={showPreview}
          buildContractContent={buildContractContent}
          deleteContract={deleteContract}
          workJournal={workJournal}
          unexpectedWorksList={unexpectedWorksList}
          isApprovedEstimateChangeStatus={isApprovedEstimateChangeStatus}
          expandedActDate={expandedActDate}
          setExpandedActDate={setExpandedActDate}
          fmtMeasure={fmtMeasure}
          newAct={newAct}
          setNewAct={setNewAct}
          masterProfiles={masterProfiles}
          createInterimAct={createInterimAct}
          buildActContent={buildActContent}
          fileSrc={fileSrc}
          uploadPhoto={uploadPhoto}
          setShowPhotoModal={setShowPhotoModal}
          setShowPayActModal={setShowPayActModal}
          deleteInterimAct={deleteInterimAct}
          buildBrigadeActContent={buildBrigadeActContent}
          estimatesList={estimatesList}
          accountingDocProject={accountingDocProject}
          setAccountingDocProject={setAccountingDocProject}
          projectPlanDone={projectPlanDone}
          materialControlSummaryForProject={materialControlSummaryForProject}
          invoices={invoices}
          warehouseInvoiceEstimateControl={warehouseInvoiceEstimateControl}
          buildPassportContent={buildPassportContent}
          showKS2={showKS2}
          buildKS3Content={buildKS3Content}
          buildJPRContent={buildJPRContent}
          buildM29Content={buildM29Content}
          buildAOSKContent={buildAOSKContent}
          buildKS11Content={buildKS11Content}
          buildKS14Content={buildKS14Content}
          buildIGDContent={buildIGDContent}
          buildExecPackageContent={buildExecPackageContent}
          buildVATBookContent={buildVATBookContent}
          buildInvoiceContent={buildInvoiceContent}
          suppliers={suppliers}
          buildM2Content={buildM2Content}
          buildM8Content={buildM8Content}
          buildMaterialRequirementContent={buildMaterialRequirementContent}
          buildSpecJournalContent={buildSpecJournalContent}
          salaryMonth={salaryMonth}
          setSalaryMonth={setSalaryMonth}
          salaryEdits={salaryEdits}
          payrollExtras={payrollExtras}
          tools={tools}
          setSalaryEdit={setSalaryEdit}
          salaryPayments={salaryPayments}
          setSalaryPayments={setSalaryPayments}
          paySalary={paySalary}
          setPayrollExtra={setPayrollExtra}
          newExpenseReport={newExpenseReport}
          setNewExpenseReport={setNewExpenseReport}
          expenseReports={expenseReports}
          auditLog={auditLog}
          setAuditLog={setAuditLog}
          tbl={tbl}
          tblH={tblH}
          tblC={tblC}
        />
      )}

      {activePage === 'personnel' && (
        <PersonnelPage
          C={C}
          ROLE_GROUPS={ROLE_GROUPS}
          ROLE_LABELS={ROLE_LABELS}
          PD_CONSENT_TEXT={PD_CONSENT_TEXT}
          UNITS={UNITS}
          API={API}
          addPiecework={addPiecework}
          addStaffDoc={addStaffDoc}
          buildContractContent={buildContractContent}
          buildPositionInstructionContent={buildPositionInstructionContent}
          btnB={btnB}
          btnG={btnG}
          btnO={btnO}
          btnR={btnR}
          calcSalary={calcSalary}
          card={card}
          contracts={contracts}
          createStaffAccessFromPrompt={createStaffAccessFromPrompt}
          daysInMonth={daysInMonth}
          deletePiecework={deletePiecework}
          deleteStaff={deleteStaff}
          editingItem={editingItem}
          expandedMaster={expandedMaster}
          expandedMasterProject={expandedMasterProject}
          expandedPieceworkProject={expandedPieceworkProject}
          expandedStaffId={expandedStaffId}
          estimatesList={estimatesList}
          fileSrc={fileSrc}
          findUserForStaff={findUserForStaff}
          fmtMeasure={fmtMeasure}
          inp={inp}
          interimActs={interimActs}
          isMobile={isMobile}
          listSearch={listSearch}
          masterProfiles={masterProfiles}
          masterRatings={masterRatings}
          matchSearch={matchSearch}
          newPiecework={newPiecework}
          newStaff={newStaff}
          newStaffDoc={newStaffDoc}
          openStaffProfile={openStaffProfile}
          pdConsents={pdConsents}
          personnelTab={personnelTab}
          piecework={piecework}
          projects={projects}
          ratemaster={ratemaster}
          resetStaffAccessPassword={resetStaffAccessPassword}
          roleColor={roleColor}
          saveStaff={saveStaff}
          setEditingItem={setEditingItem}
          setExpandedMaster={setExpandedMaster}
          setExpandedMasterProject={setExpandedMasterProject}
          setExpandedPieceworkProject={setExpandedPieceworkProject}
          setListSearch={setListSearch}
          setNewPiecework={setNewPiecework}
          setNewStaff={setNewStaff}
          setNewStaffDoc={setNewStaffDoc}
          setPersonnelTab={setPersonnelTab}
          setShowForm={setShowForm}
          setShowPhotoModal={setShowPhotoModal}
          setShowPiecework={setShowPiecework}
          setShowStaffDocForm={setShowStaffDocForm}
          setStaffProfile={setStaffProfile}
          setStaffExpandedSections={setStaffExpandedSections}
          showForm={showForm}
          showPiecework={showPiecework}
          showPreview={showPreview}
          showStaffDocForm={showStaffDocForm}
          staff={staff}
          staffExpandedSections={staffExpandedSections}
          staffProfile={staffProfile}
          staffProfileLoading={staffProfileLoading}
          tbl={tbl}
          tblC={tblC}
          tblH={tblH}
          timesheet={timesheet}
          toggleDay={toggleDay}
          uploadPhoto={uploadPhoto}
          users={users}
          workJournal={workJournal}
          workedDays={workedDays}
        />
      )}
    </>
  );
}
