import React from 'react';
import {
  SupplyPage,
  WarehousePage,
} from '../app/lazyComponents';

export default function AppOperationsPages({ activePage, ui, constants, state, actions }) {
  const { API, C, badge, btnB, btnG, btnGr, btnO, btnR, card, inp, isMobile, tbl, tblC, tblH } = ui;
  const { MATERIAL_CATEGORIES, SUPPLIER_CATEGORIES, TOOL_STATUSES, UNITS, VAT_OPTIONS } = constants;
  const {
    compareLoadingReqId,
    compareResultByReq,
    deliveryAiLoadingId,
    deliveryAiResultById,
    editingItem,
    estimatesList,
    expandedProject,
    fileSrc,
    history,
    inventory,
    invoices,
    listSearch,
    materialReconciliationRows,
    materials,
    materialsPage,
    materialTransfers,
    newInventory,
    newInvoice,
    newMovement,
    newSupplier,
    newSupplierInvoice,
    newSupplyReq,
    newTool,
    newTransfer,
    newWarehouse,
    priceHints,
    projects,
    receiveForm,
    receivingDeliveryId,
    selectedInventory,
    selectedWarehouseProject,
    showForm,
    showSupplyForm,
    showTransferForm,
    staff,
    suppliers,
    supplierCatalog,
    supplierInvoices,
    supplierOffers,
    supplyAiLoading,
    supplyAiText,
    supplyClaims,
    supplyCollapsedProjects,
    supplyDeliveries,
    supplyExpandedId,
    supplyRejectId,
    supplyRejectReason,
    supplyRequests,
    supplyRequestOrigin,
    supplyStockCheck,
    supplyTab,
    supplyTemplates,
    toolHistory,
    tools,
    toolsTab,
    user,
    users,
    warehouseInvoiceItems,
    warehouseMain,
    warehouseMovements,
    warehouses,
    warehouseTab,
  } = state;
  const {
    _normalizeUnit,
    applySupplyTemplate,
    applyWarehouseMovement,
    approveSupplyAsDirector,
    askSupplyAi,
    buildInventoryDoc,
    buildInvoiceContent,
    buildMaterialRequirementContent,
    buildMovementDoc,
    cancelSupply,
    confirmSupplyAsProrab,
    convertUnits,
    createSupplyReq,
    deleteMainMaterial,
    deleteMaterial,
    deleteSupplier,
    deleteSupplyTemplate,
    deleteTool,
    deleteWarehouse,
    exportToExcel,
    fetchPriceHint,
    getProjectEstimateWorkOptions,
    getProjectWorkPackageOptions,
    isFinanceRole,
    isLeadership,
    isProrab,
    isSupplyDeliveryInvoice,
    loadAll,
    loadMaterialsPage,
    loadSupplyStockCheck,
    matchSearch,
    materialControlSummaryForProject,
    notify,
    openReceiveInvoice,
    openRequestKpModal,
    parseOfferItems,
    parseSupplyItems,
    receiveSupplyDelivery,
    refreshData,
    rejectSupplierOffer,
    rejectSupply,
    renderInvoiceControlActions,
    renderMaterialReconciliationPanel,
    renderSupplyPlanningHint,
    renderSupplyRequestOrigin,
    runCompareKp,
    runDeliveryAiCheck,
    saveInvoiceNew,
    saveSupplier,
    saveSupplyTemplate,
    saveTool,
    saveWarehouse,
    selectSupplierOffer,
    withdrawSupplierOffer,
    setDeliveryAiLoadingId,
    setDeliveryAiResultById,
    setEditingItem,
    setExpandedProject,
    setGeneratedInviteLink,
    setListSearch,
    setMaterialTransfers,
    setMaterials,
    setNewInventory,
    setNewInvoice,
    setNewMovement,
    setNewSupplier,
    setNewSupplierInvoice,
    setNewSupplyReq,
    setNewTool,
    setNewTransfer,
    setNewWarehouse,
    setReceiveForm,
    setReceivingDeliveryId,
    setSelectedInventory,
    setSelectedWarehouseProject,
    setShowForm,
    setShowIssueToolModal,
    setShowPhotoModal,
    setShowQRModal,
    setShowReturnToolModal,
    setSverkaModal,
    setShowSupplierInviteModal,
    setShowSupplyForm,
    setShowTransferForm,
    setSupplierInviteForm,
    setSupplyCollapsedProjects,
    setSupplyExpandedId,
    setSupplyRejectId,
    setSupplyRejectReason,
    setSupplyTab,
    setToolsTab,
    setWarehouseMain,
    setWarehouseTab,
    showPreview,
    toNum,
    uploadPhoto,
    visibleActiveProjects,
    warehouseInvoiceEstimateControl,
  } = actions;

  return (
    <>
      {activePage === 'warehouse' && (
        <WarehousePage
          isMobile={isMobile}
          warehouseTab={warehouseTab}
          setWarehouseTab={setWarehouseTab}
          setShowForm={setShowForm}
          btnO={btnO}
          btnG={btnG}
          C={C}
          badge={badge}
          btnB={btnB}
          buildMaterialRequirementContent={buildMaterialRequirementContent}
          card={card}
          exportToExcel={exportToExcel}
          isFinanceRole={isFinanceRole}
          isLeadership={isLeadership}
          materialControlSummaryForProject={materialControlSummaryForProject}
          materialReconciliationRows={materialReconciliationRows}
          parseSupplyItems={parseSupplyItems}
          projects={projects}
          getProjectWorkPackageOptions={getProjectWorkPackageOptions}
          getProjectEstimateWorkOptions={getProjectEstimateWorkOptions}
          setSelectedWarehouseProject={setSelectedWarehouseProject}
          visibleActiveProjects={visibleActiveProjects}
          showForm={showForm}
          editingItem={editingItem}
          setEditingItem={setEditingItem}
          newWarehouse={newWarehouse}
          setNewWarehouse={setNewWarehouse}
          saveWarehouse={saveWarehouse}
          deleteWarehouse={deleteWarehouse}
          warehouses={warehouses}
          inp={inp}
          btnR={btnR}
          btnGr={btnGr}
          tbl={tbl}
          tblH={tblH}
          tblC={tblC}
          selectedWarehouseProject={selectedWarehouseProject}
          materials={materials}
          materialsPage={materialsPage}
          loadMaterialsPage={loadMaterialsPage}
          openReceiveInvoice={openReceiveInvoice}
          user={user}
          materialTransfers={materialTransfers}
          setMaterialTransfers={setMaterialTransfers}
          setNewTransfer={setNewTransfer}
          setShowTransferForm={setShowTransferForm}
          renderMaterialReconciliationPanel={renderMaterialReconciliationPanel}
          deleteMaterial={deleteMaterial}
          showTransferForm={showTransferForm}
          newTransfer={newTransfer}
          warehouseMain={warehouseMain}
          supplyRequests={supplyRequests}
          _normalizeUnit={_normalizeUnit}
          convertUnits={convertUnits}
          staff={staff}
          setWarehouseMain={setWarehouseMain}
          setMaterials={setMaterials}
          notify={notify}
          newInvoice={newInvoice}
          setNewInvoice={setNewInvoice}
          suppliers={suppliers}
          estimatesList={estimatesList}
          invoices={invoices}
          saveInvoiceNew={saveInvoiceNew}
          uploadPhoto={uploadPhoto}
          fileSrc={fileSrc}
          setShowPhotoModal={setShowPhotoModal}
          setSverkaModal={setSverkaModal}
          warehouseInvoiceItems={warehouseInvoiceItems}
          isSupplyDeliveryInvoice={isSupplyDeliveryInvoice}
          warehouseInvoiceEstimateControl={warehouseInvoiceEstimateControl}
          renderInvoiceControlActions={renderInvoiceControlActions}
          showPreview={showPreview}
          buildInvoiceContent={buildInvoiceContent}
          setShowQRModal={setShowQRModal}
          VAT_OPTIONS={VAT_OPTIONS}
          UNITS={UNITS}
          MATERIAL_CATEGORIES={MATERIAL_CATEGORIES}
          history={history}
          listSearch={listSearch}
          setListSearch={setListSearch}
          matchSearch={matchSearch}
          deleteMainMaterial={deleteMainMaterial}
          warehouseMovements={warehouseMovements}
          newMovement={newMovement}
          setNewMovement={setNewMovement}
          applyWarehouseMovement={applyWarehouseMovement}
          buildMovementDoc={buildMovementDoc}
          toolsTab={toolsTab}
          setToolsTab={setToolsTab}
          newTool={newTool}
          setNewTool={setNewTool}
          saveTool={saveTool}
          deleteTool={deleteTool}
          tools={tools}
          toolHistory={toolHistory}
          isProrab={isProrab}
          setShowIssueToolModal={setShowIssueToolModal}
          setShowReturnToolModal={setShowReturnToolModal}
          TOOL_STATUSES={TOOL_STATUSES}
          newInventory={newInventory}
          setNewInventory={setNewInventory}
          selectedInventory={selectedInventory}
          setSelectedInventory={setSelectedInventory}
          inventory={inventory}
          buildInventoryDoc={buildInventoryDoc}
          refreshData={refreshData}
        />
      )}

      {activePage === 'supply' && (
        <SupplyPage
          API={API}
          C={C}
          card={card}
          inp={inp}
          isMobile={isMobile}
          tblH={tblH}
          tblC={tblC}
          btnO={btnO}
          btnG={btnG}
          btnB={btnB}
          btnGr={btnGr}
          btnR={btnR}
          badge={badge}
          user={user}
          users={users}
          isLeadership={isLeadership}
          isFinanceRole={isFinanceRole}
          showSupplyForm={showSupplyForm}
          setShowSupplyForm={setShowSupplyForm}
          showForm={showForm}
          setShowForm={setShowForm}
          supplyTab={supplyTab}
          setSupplyTab={setSupplyTab}
          supplyRequests={supplyRequests}
          listSearch={listSearch}
          setListSearch={setListSearch}
          matchSearch={matchSearch}
          supplyTemplates={supplyTemplates}
          applySupplyTemplate={applySupplyTemplate}
          deleteSupplyTemplate={deleteSupplyTemplate}
          newSupplyReq={newSupplyReq}
          setNewSupplyReq={setNewSupplyReq}
          priceHints={priceHints}
          fetchPriceHint={fetchPriceHint}
          UNITS={UNITS}
          projects={projects}
          getProjectWorkPackageOptions={getProjectWorkPackageOptions}
          renderSupplyPlanningHint={renderSupplyPlanningHint}
          createSupplyReq={createSupplyReq}
          saveSupplyTemplate={saveSupplyTemplate}
          supplyCollapsedProjects={supplyCollapsedProjects}
          setSupplyCollapsedProjects={setSupplyCollapsedProjects}
          parseSupplyItems={parseSupplyItems}
          renderSupplyRequestOrigin={renderSupplyRequestOrigin}
          supplyRequestOrigin={supplyRequestOrigin}
          supplyExpandedId={supplyExpandedId}
          setSupplyExpandedId={setSupplyExpandedId}
          confirmSupplyAsProrab={confirmSupplyAsProrab}
          approveSupplyAsDirector={approveSupplyAsDirector}
          openRequestKpModal={openRequestKpModal}
          loadSupplyStockCheck={loadSupplyStockCheck}
          setSupplyRejectId={setSupplyRejectId}
          supplyRejectId={supplyRejectId}
          supplyRejectReason={supplyRejectReason}
          setSupplyRejectReason={setSupplyRejectReason}
          rejectSupply={rejectSupply}
          cancelSupply={cancelSupply}
          supplyStockCheck={supplyStockCheck}
          askSupplyAi={askSupplyAi}
          supplyAiLoading={supplyAiLoading}
          supplyAiText={supplyAiText}
          supplierOffers={supplierOffers}
          compareResultByReq={compareResultByReq}
          compareLoadingReqId={compareLoadingReqId}
          runCompareKp={runCompareKp}
          suppliers={suppliers}
          fileSrc={fileSrc}
          parseOfferItems={parseOfferItems}
          selectSupplierOffer={selectSupplierOffer}
          rejectSupplierOffer={rejectSupplierOffer}
          withdrawSupplierOffer={withdrawSupplierOffer}
          supplierInvoices={supplierInvoices}
          newSupplierInvoice={newSupplierInvoice}
          setNewSupplierInvoice={setNewSupplierInvoice}
          expandedProject={expandedProject}
          setExpandedProject={setExpandedProject}
          loadAll={loadAll}
          toNum={toNum}
          supplierCategories={SUPPLIER_CATEGORIES}
          editingItem={editingItem}
          setEditingItem={setEditingItem}
          newSupplier={newSupplier}
          setNewSupplier={setNewSupplier}
          saveSupplier={saveSupplier}
          deleteSupplier={deleteSupplier}
          setSupplierInviteForm={setSupplierInviteForm}
          setGeneratedInviteLink={setGeneratedInviteLink}
          setShowSupplierInviteModal={setShowSupplierInviteModal}
          supplierCatalog={supplierCatalog}
          supplyClaims={supplyClaims}
          supplyDeliveries={supplyDeliveries}
          receivingDeliveryId={receivingDeliveryId}
          setReceivingDeliveryId={setReceivingDeliveryId}
          receiveForm={receiveForm}
          setReceiveForm={setReceiveForm}
          deliveryAiLoadingId={deliveryAiLoadingId}
          setDeliveryAiLoadingId={setDeliveryAiLoadingId}
          deliveryAiResultById={deliveryAiResultById}
          setDeliveryAiResultById={setDeliveryAiResultById}
          runDeliveryAiCheck={runDeliveryAiCheck}
          receiveSupplyDelivery={receiveSupplyDelivery}
          invoices={invoices}
          showPreview={showPreview}
          buildInvoiceContent={buildInvoiceContent}
          uploadPhoto={uploadPhoto}
        />
      )}
    </>
  );
}
