import React from 'react';
import {
  AccountableExpenseReportModal,
  AccountablePaymentModal,
  AiChatModal,
  EstimateChatModal,
  EstimateDistributeModal,
  EstimateVersionHistoryModal,
  GenerateEstimateModal,
  GeneratePricelistModal,
  ManualExpenseModal,
  OwnExpenseFormModal,
  PricelistFromEstimateModal,
  QuickActionsModal,
  ReceiveMaterialDialog,
  ReimburseModal,
  RequestKpModal,
  ScanInvoiceModal,
  ScannedInvoiceFormModal,
  SupplierInviteModal,
  SverkaModal,
} from '../app/lazyComponents';

export default function AppWorkflowModals({ ui, constants, state, actions }) {
  const {
    API,
    C,
    badge,
    btnB,
    btnG,
    btnO,
    btnR,
    card,
    darkMode,
    inp,
    isMobile,
  } = ui;
  const {
    estimatePackages,
    expenseCategories,
    roleLabels,
    supplierCategories,
    units,
  } = constants;
  const {
    activeEstimateFromList,
    addExpenseProject,
    aiInput,
    aiLoading,
    aiMessages,
    creatingFromEstimate,
    distributeAssignments,
    distributeBrigades,
    distributing,
    estimateChatInput,
    estimateChatLoading,
    estimateChatMessages,
    estimateVersions,
    estimatesList,
    expenseSubmitting,
    fileSrc,
    fromEstimateForm,
    generateForm,
    generatePricelistForm,
    generatedInviteLink,
    generating,
    generatingPricelist,
    isFinanceRole,
    isGlobalEstimateTemplate,
    newAccountable,
    newDistributeBrigade,
    newExpense,
    newInvoice,
    newManualExpense,
    newOwnExpense,
    ownExpenses,
    pricelists,
    projects,
    reportingPayment,
    requestKpLoading,
    scanningInvoice,
    selectedEstimate,
    selectedSupplierIds,
    selectedVersionsToCompare,
    showAccountableForm,
    showAiChat,
    showDistribute,
    showEstimateChat,
    showFromEstimate,
    showGenerateEstimate,
    showGeneratePricelist,
    showOwnExpenseForm,
    showPreview,
    showQuickActions,
    showReceiveDialog,
    showReimburseModal,
    showRequestKpModal,
    showScanInvoice,
    showScannedInvoiceForm,
    showSupplierInviteModal,
    showVersionHistory,
    suggestedSuppliers,
    suppliers,
    supplierInviteForm,
    supplyRequests,
    sverkaModal,
    user,
    users,
    staff,
    visibleActiveProjects,
  } = state;
  const {
    appendPhotos,
    applyEstimateActivationState,
    autoReconcileEstimateChanges,
    buildEstimateDiffContent,
    clearEstimateChatHistory,
    createSupplierInvite,
    enrichEstimateMeasurementBasis,
    estimateItemTotal,
    getProjectEstimateWorkOptions,
    getProjectWorkPackageOptions,
    loadAll,
    loadPricelistItems,
    navigateTo,
    nextEstimateVersionFor,
    openReceiveInvoice,
    parseSupplyItems,
    queueEstimateDiffReviewTask,
    queueEstimateNormReviewTask,
    queueEstimateQualityReviewTask,
    renderSupplyRequestOrigin,
    sameEstimateGroup,
    saveInvoiceNew,
    sendAiAssistantMessage,
    sendEstimateChatMessage,
    sendKpRequest,
    setActivePage,
    setAddExpenseProject,
    setAiInput,
    setAiLoading,
    setAiMessages,
    setCreatingFromEstimate,
    setDistributeAssignments,
    setDistributeBrigades,
    setDistributing,
    setEstimateChatInput,
    setEstimatesList,
    setExpenseSubmitting,
    setFromEstimateForm,
    setGenerateForm,
    setGeneratePricelistForm,
    setGeneratedInviteLink,
    setGenerating,
    setGeneratingPricelist,
    setMaterialTransfers,
    setNewAccountable,
    setNewDistributeBrigade,
    setNewExpense,
    setNewInvoice,
    setNewManualExpense,
    setNewOwnExpense,
    setReportingPayment,
    setScanningInvoice,
    setSelectedEstimate,
    setSelectedPricelist,
    setSelectedSupplierIds,
    setSelectedVersionsToCompare,
    setSelectedWarehouseProject,
    setShowAccountableForm,
    setShowAiAssistant,
    setShowAiChat,
    setShowChatPanel,
    setShowDistribute,
    setShowEstimateChat,
    setShowFromEstimate,
    setShowGenerateEstimate,
    setShowGeneratePricelist,
    setShowOwnExpenseForm,
    setShowPhotoModal,
    setShowQuickActions,
    setShowReceiveDialog,
    setShowReimburseModal,
    setShowRequestKpModal,
    setShowScanInvoice,
    setShowScannedInvoiceForm,
    setShowSupplierInviteModal,
    setShowTransferForm,
    setShowVersionHistory,
    setSverkaModal,
    setSupplierInviteForm,
    setWarehouseTab,
  } = actions;

  return (
    <React.Suspense fallback={null}>
      {sverkaModal && (
        <SverkaModal sverkaModal={sverkaModal} setSverkaModal={setSverkaModal} btnO={btnO} />
      )}

      {showAiChat && (
        <AiChatModal
          showAiChat={showAiChat}
          isMobile={isMobile}
          C={C}
          inp={inp}
          btnO={btnO}
          aiMessages={aiMessages}
          aiLoading={aiLoading}
          aiInput={aiInput}
          setAiInput={setAiInput}
          setShowAiChat={setShowAiChat}
          onSend={sendAiAssistantMessage}
        />
      )}

      {showSupplierInviteModal && (
        <SupplierInviteModal
          showSupplierInviteModal={showSupplierInviteModal}
          setShowSupplierInviteModal={setShowSupplierInviteModal}
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          generatedInviteLink={generatedInviteLink}
          setGeneratedInviteLink={setGeneratedInviteLink}
          supplierInviteForm={supplierInviteForm}
          setSupplierInviteForm={setSupplierInviteForm}
          suppliers={suppliers}
          supplierCategories={supplierCategories}
          createSupplierInvite={createSupplierInvite}
        />
      )}

      {showRequestKpModal && (
        <RequestKpModal
          showRequestKpModal={showRequestKpModal}
          setShowRequestKpModal={setShowRequestKpModal}
          C={C}
          card={card}
          btnG={btnG}
          btnO={btnO}
          badge={badge}
          supplyRequests={supplyRequests}
          parseSupplyItems={parseSupplyItems}
          renderSupplyRequestOrigin={renderSupplyRequestOrigin}
          requestKpLoading={requestKpLoading}
          suggestedSuppliers={suggestedSuppliers}
          selectedSupplierIds={selectedSupplierIds}
          setSelectedSupplierIds={setSelectedSupplierIds}
          sendKpRequest={sendKpRequest}
        />
      )}

      {showReimburseModal && (
        <ReimburseModal
          showReimburseModal={showReimburseModal}
          setShowReimburseModal={setShowReimburseModal}
          C={C}
          card={card}
          btnG={btnG}
          btnO={btnO}
          btnR={btnR}
          ownExpenses={ownExpenses}
          users={users}
          staff={staff}
          roleLabels={roleLabels}
          expenseCategories={expenseCategories}
          fileSrc={fileSrc}
          setShowPhotoModal={setShowPhotoModal}
          API={API}
          user={user}
          loadAll={loadAll}
        />
      )}

      {reportingPayment && (
        <AccountableExpenseReportModal
          reportingPayment={reportingPayment}
          setReportingPayment={setReportingPayment}
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          projects={projects}
          expenseCategories={expenseCategories}
          newExpense={newExpense}
          setNewExpense={setNewExpense}
          appendPhotos={appendPhotos}
          fileSrc={fileSrc}
          expenseSubmitting={expenseSubmitting}
          setExpenseSubmitting={setExpenseSubmitting}
          API={API}
          user={user}
          loadAll={loadAll}
        />
      )}

      {addExpenseProject && (
        <ManualExpenseModal
          addExpenseProject={addExpenseProject}
          setAddExpenseProject={setAddExpenseProject}
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          newManualExpense={newManualExpense}
          setNewManualExpense={setNewManualExpense}
          isFinanceRole={isFinanceRole}
          expenseCategories={expenseCategories}
          projects={projects}
          visibleActiveProjects={visibleActiveProjects}
          appendPhotos={appendPhotos}
          fileSrc={fileSrc}
          setShowPhotoModal={setShowPhotoModal}
          API={API}
          user={user}
          loadAll={loadAll}
        />
      )}

      {showAccountableForm && (
        <AccountablePaymentModal
          showAccountableForm={showAccountableForm}
          setShowAccountableForm={setShowAccountableForm}
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          projects={projects}
          users={users}
          newAccountable={newAccountable}
          setNewAccountable={setNewAccountable}
          API={API}
          user={user}
          loadAll={loadAll}
        />
      )}

      {showDistribute && (
        <EstimateDistributeModal
          showDistribute={showDistribute}
          setShowDistribute={setShowDistribute}
          selectedEstimate={selectedEstimate}
          distributing={distributing}
          setDistributing={setDistributing}
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          btnB={btnB}
          distributeBrigades={distributeBrigades}
          setDistributeBrigades={setDistributeBrigades}
          newDistributeBrigade={newDistributeBrigade}
          setNewDistributeBrigade={setNewDistributeBrigade}
          pricelists={pricelists}
          staff={staff}
          distributeAssignments={distributeAssignments}
          setDistributeAssignments={setDistributeAssignments}
          API={API}
          loadAll={loadAll}
        />
      )}

      {showFromEstimate && (
        <PricelistFromEstimateModal
          showFromEstimate={showFromEstimate}
          setShowFromEstimate={setShowFromEstimate}
          creatingFromEstimate={creatingFromEstimate}
          setCreatingFromEstimate={setCreatingFromEstimate}
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          fromEstimateForm={fromEstimateForm}
          setFromEstimateForm={setFromEstimateForm}
          estimatesList={estimatesList}
          API={API}
          loadAll={loadAll}
          setSelectedPricelist={setSelectedPricelist}
          loadPricelistItems={loadPricelistItems}
        />
      )}

      {showGeneratePricelist && (
        <GeneratePricelistModal
          showGeneratePricelist={showGeneratePricelist}
          setShowGeneratePricelist={setShowGeneratePricelist}
          generatingPricelist={generatingPricelist}
          setGeneratingPricelist={setGeneratingPricelist}
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          generatePricelistForm={generatePricelistForm}
          setGeneratePricelistForm={setGeneratePricelistForm}
          API={API}
          loadAll={loadAll}
          setSelectedPricelist={setSelectedPricelist}
          loadPricelistItems={loadPricelistItems}
        />
      )}

      {showGenerateEstimate && (
        <GenerateEstimateModal
          showGenerateEstimate={showGenerateEstimate}
          setShowGenerateEstimate={setShowGenerateEstimate}
          generating={generating}
          setGenerating={setGenerating}
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          generateForm={generateForm}
          setGenerateForm={setGenerateForm}
          projects={projects}
          pricelists={pricelists}
          estimatePackages={estimatePackages}
          nextEstimateVersionFor={nextEstimateVersionFor}
          API={API}
          enrichEstimateMeasurementBasis={enrichEstimateMeasurementBasis}
          estimatesList={estimatesList}
          setEstimatesList={setEstimatesList}
          setSelectedEstimate={setSelectedEstimate}
          activeEstimateFromList={activeEstimateFromList}
          isGlobalEstimateTemplate={isGlobalEstimateTemplate}
          sameEstimateGroup={sameEstimateGroup}
          applyEstimateActivationState={applyEstimateActivationState}
          queueEstimateDiffReviewTask={queueEstimateDiffReviewTask}
          autoReconcileEstimateChanges={autoReconcileEstimateChanges}
          queueEstimateQualityReviewTask={queueEstimateQualityReviewTask}
          queueEstimateNormReviewTask={queueEstimateNormReviewTask}
        />
      )}

      {showEstimateChat && (
        <EstimateChatModal
          showEstimateChat={showEstimateChat}
          setShowEstimateChat={setShowEstimateChat}
          selectedEstimate={selectedEstimate}
          C={C}
          card={card}
          inp={inp}
          btnG={btnG}
          btnO={btnO}
          isMobile={isMobile}
          darkMode={darkMode}
          clearEstimateChatHistory={clearEstimateChatHistory}
          estimateChatMessages={estimateChatMessages}
          estimateChatLoading={estimateChatLoading}
          estimateChatInput={estimateChatInput}
          setEstimateChatInput={setEstimateChatInput}
          sendEstimateChatMessage={sendEstimateChatMessage}
        />
      )}

      {showVersionHistory && (
        <EstimateVersionHistoryModal
          showVersionHistory={showVersionHistory}
          setShowVersionHistory={setShowVersionHistory}
          selectedEstimate={selectedEstimate}
          estimateVersions={estimateVersions}
          selectedVersionsToCompare={selectedVersionsToCompare}
          setSelectedVersionsToCompare={setSelectedVersionsToCompare}
          isMobile={isMobile}
          C={C}
          card={card}
          btnB={btnB}
          btnG={btnG}
          btnO={btnO}
          API={API}
          user={user}
          setSelectedEstimate={setSelectedEstimate}
          setEstimatesList={setEstimatesList}
          showPreview={showPreview}
          buildEstimateDiffContent={buildEstimateDiffContent}
          estimateItemTotal={estimateItemTotal}
          setShowAiChat={setShowAiChat}
          setAiMessages={setAiMessages}
          setAiLoading={setAiLoading}
        />
      )}

      {showReceiveDialog && (
        <ReceiveMaterialDialog
          showReceiveDialog={showReceiveDialog}
          setShowReceiveDialog={setShowReceiveDialog}
          setShowScanInvoice={setShowScanInvoice}
          setShowScannedInvoiceForm={setShowScannedInvoiceForm}
          C={C}
          card={card}
          btnB={btnB}
          btnG={btnG}
        />
      )}

      {showScannedInvoiceForm && (
        <ScannedInvoiceFormModal
          showScannedInvoiceForm={showScannedInvoiceForm}
          setShowScannedInvoiceForm={setShowScannedInvoiceForm}
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          btnR={btnR}
          newInvoice={newInvoice}
          setNewInvoice={setNewInvoice}
          projects={projects}
          getProjectWorkPackageOptions={getProjectWorkPackageOptions}
          getProjectEstimateWorkOptions={getProjectEstimateWorkOptions}
          units={units}
          saveInvoiceNew={saveInvoiceNew}
        />
      )}

      {showScanInvoice && (
        <ScanInvoiceModal
          showScanInvoice={showScanInvoice}
          setShowScanInvoice={setShowScanInvoice}
          setShowScannedInvoiceForm={setShowScannedInvoiceForm}
          C={C}
          card={card}
          btnG={btnG}
          scanningInvoice={scanningInvoice}
          setScanningInvoice={setScanningInvoice}
          API={API}
          user={user}
          newInvoice={newInvoice}
          setNewInvoice={setNewInvoice}
          projects={projects}
        />
      )}

      {showOwnExpenseForm && (
        <OwnExpenseFormModal
          showOwnExpenseForm={showOwnExpenseForm}
          setShowOwnExpenseForm={setShowOwnExpenseForm}
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          projectOptions={projects}
          expenseCategories={expenseCategories}
          newOwnExpense={newOwnExpense}
          setNewOwnExpense={setNewOwnExpense}
          appendPhotos={appendPhotos}
          fileSrc={fileSrc}
          API={API}
          user={user}
          loadAll={loadAll}
        />
      )}

      {showQuickActions && (
        <QuickActionsModal
          showQuickActions={showQuickActions}
          setShowQuickActions={setShowQuickActions}
          C={C}
          btnG={btnG}
          user={user}
          projects={projects}
          visibleActiveProjects={visibleActiveProjects}
          openReceiveInvoice={openReceiveInvoice}
          setActivePage={setActivePage}
          setWarehouseTab={setWarehouseTab}
          navigateTo={navigateTo}
          API={API}
          setMaterialTransfers={setMaterialTransfers}
          setShowTransferForm={setShowTransferForm}
          setSelectedWarehouseProject={setSelectedWarehouseProject}
          setAddExpenseProject={setAddExpenseProject}
          setNewManualExpense={setNewManualExpense}
          setShowOwnExpenseForm={setShowOwnExpenseForm}
          setShowChatPanel={setShowChatPanel}
          setShowAiAssistant={setShowAiAssistant}
        />
      )}
    </React.Suspense>
  );
}
