import React from 'react';
import WarehouseInvoicesPanel from './WarehouseInvoicesPanel';
import WarehouseMainStockPanel from './WarehouseMainStockPanel';
import WarehouseCompanyWarehousesPanel from './WarehouseCompanyWarehousesPanel';
import WarehouseHistoryPanel from './WarehouseHistoryPanel';
import WarehouseOperationsPanel from './WarehouseOperationsPanel';
import WarehouseObjectsPanel from './WarehouseObjectsPanel';
import WarehouseTabsNav from './WarehouseTabsNav';
import WarehouseMaterialControlOverview from './WarehouseMaterialControlOverview';

export default function WarehousePage(props) {
  const {
    warehouseTab,
    setWarehouseTab,
    setShowForm,
    btnO,
    btnG,
    C,
    badge,
    btnB,
    buildMaterialRequirementContent,
    card,
    exportToExcel,
    isFinanceRole,
    isLeadership,
    materialControlSummaryForProject,
    materialReconciliationRows,
    projects,
    setSelectedWarehouseProject,
    visibleActiveProjects,
    showForm,
    editingItem,
    setEditingItem,
    newWarehouse,
    setNewWarehouse,
    saveWarehouse,
    deleteWarehouse,
    inp,
    btnR,
    btnGr,
    tbl,
    tblH,
    tblC,
    selectedWarehouseProject,
    materials,
    openReceiveInvoice,
    user,
    setMaterialTransfers,
    setNewTransfer,
    showTransferForm,
    setShowTransferForm,
    renderMaterialReconciliationPanel,
    deleteMaterial,
    newTransfer,
    warehouseMain,
    supplyRequests,
    _normalizeUnit,
    convertUnits,
    staff,
    setWarehouseMain,
    setMaterials,
    notify,
    newInvoice,
    setNewInvoice,
    suppliers,
    estimatesList,
    getProjectWorkPackageOptions,
    getProjectEstimateWorkOptions,
    invoices,
    saveInvoiceNew,
    uploadPhoto,
    fileSrc,
    setShowPhotoModal,
    setSverkaModal,
    warehouseInvoiceItems,
    isSupplyDeliveryInvoice,
    warehouseInvoiceEstimateControl,
    renderInvoiceControlActions,
    showPreview,
    buildInvoiceContent,
    setShowQRModal,
    VAT_OPTIONS,
    UNITS,
    MATERIAL_CATEGORIES,
    history,
    listSearch,
    setListSearch,
    matchSearch,
    deleteMainMaterial,
    warehouseMovements,
    newMovement,
    setNewMovement,
    applyWarehouseMovement,
    buildMovementDoc,
    toolsTab,
    setToolsTab,
    newTool,
    setNewTool,
    saveTool,
    deleteTool,
    tools,
    toolHistory,
    isProrab,
    setShowIssueToolModal,
    setShowReturnToolModal,
    TOOL_STATUSES,
    newInventory,
    setNewInventory,
    selectedInventory,
    setSelectedInventory,
    inventory,
    buildInventoryDoc,
    refreshData,
    isMobile,
  } = props;

  return (
    <div>
      <WarehouseTabsNav
        warehouseTab={warehouseTab}
        setWarehouseTab={setWarehouseTab}
        setShowForm={setShowForm}
        btnO={btnO}
        btnG={btnG}
      />

      {warehouseTab === 'control' && (
        <WarehouseMaterialControlOverview
          C={C}
          badge={badge}
          btnB={btnB}
          btnG={btnG}
          buildMaterialRequirementContent={buildMaterialRequirementContent}
          card={card}
          exportToExcel={exportToExcel}
          isFinanceRole={isFinanceRole}
          isLeadership={isLeadership}
          materialControlSummaryForProject={materialControlSummaryForProject}
          materialReconciliationRows={materialReconciliationRows}
          projects={projects}
          setSelectedWarehouseProject={setSelectedWarehouseProject}
          setWarehouseTab={setWarehouseTab}
          showPreview={showPreview}
          visibleActiveProjects={visibleActiveProjects}
        />
      )}

      {warehouseTab === 'warehouses' && (
        <WarehouseCompanyWarehousesPanel
          warehouses={props.warehouses}
          showForm={showForm}
          setShowForm={setShowForm}
          editingItem={editingItem}
          setEditingItem={setEditingItem}
          newWarehouse={newWarehouse}
          setNewWarehouse={setNewWarehouse}
          saveWarehouse={saveWarehouse}
          deleteWarehouse={deleteWarehouse}
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          btnR={btnR}
        />
      )}

      {warehouseTab === 'objects' && (
        <WarehouseObjectsPanel
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          btnGr={btnGr}
          btnR={btnR}
          tbl={tbl}
          tblH={tblH}
          tblC={tblC}
          badge={badge}
          selectedWarehouseProject={selectedWarehouseProject}
          setSelectedWarehouseProject={setSelectedWarehouseProject}
          visibleActiveProjects={visibleActiveProjects}
          projects={projects}
          materials={materials}
          openReceiveInvoice={openReceiveInvoice}
          isLeadership={isLeadership}
          user={user}
          setMaterialTransfers={setMaterialTransfers}
          setNewTransfer={setNewTransfer}
          setShowTransferForm={setShowTransferForm}
          exportToExcel={exportToExcel}
          renderMaterialReconciliationPanel={renderMaterialReconciliationPanel}
          deleteMaterial={deleteMaterial}
          showTransferForm={showTransferForm}
          newTransfer={newTransfer}
          warehouseMain={warehouseMain}
          supplyRequests={supplyRequests}
          _normalizeUnit={_normalizeUnit}
          convertUnits={convertUnits}
          staff={staff}
          getProjectWorkPackageOptions={getProjectWorkPackageOptions}
          setWarehouseMain={setWarehouseMain}
          setMaterials={setMaterials}
          notify={notify}
          isMobile={isMobile}
        />
      )}

      {warehouseTab === 'main' && (
        <WarehouseMainStockPanel
          warehouseMain={warehouseMain}
          listSearch={listSearch}
          setListSearch={setListSearch}
          matchSearch={matchSearch}
          openReceiveInvoice={openReceiveInvoice}
          exportToExcel={exportToExcel}
          deleteMainMaterial={deleteMainMaterial}
          C={C}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          btnR={btnR}
          tbl={tbl}
          tblH={tblH}
          tblC={tblC}
          badge={badge}
        />
      )}

      {warehouseTab === 'invoices' && (
        <WarehouseInvoicesPanel
          showForm={showForm}
          setShowForm={setShowForm}
          newInvoice={newInvoice}
          setNewInvoice={setNewInvoice}
          suppliers={suppliers}
          projects={projects}
          estimatesList={estimatesList}
          getProjectWorkPackageOptions={getProjectWorkPackageOptions}
          getProjectEstimateWorkOptions={getProjectEstimateWorkOptions}
          invoices={invoices}
          saveInvoiceNew={saveInvoiceNew}
          uploadPhoto={uploadPhoto}
          fileSrc={fileSrc}
          setShowPhotoModal={setShowPhotoModal}
          setSverkaModal={setSverkaModal}
          warehouseInvoiceItems={warehouseInvoiceItems}
          isSupplyDeliveryInvoice={isSupplyDeliveryInvoice}
          warehouseInvoiceEstimateControl={warehouseInvoiceEstimateControl}
          renderInvoiceControlActions={renderInvoiceControlActions}
          showPreview={showPreview}
          buildInvoiceContent={buildInvoiceContent}
          setShowQRModal={setShowQRModal}
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          btnB={btnB}
          btnR={btnR}
          tbl={tbl}
          tblH={tblH}
          tblC={tblC}
          VAT_OPTIONS={VAT_OPTIONS}
          UNITS={UNITS}
          MATERIAL_CATEGORIES={MATERIAL_CATEGORIES}
        />
      )}

      {warehouseTab === 'history' && (
        <WarehouseHistoryPanel
          history={history}
          listSearch={listSearch}
          matchSearch={matchSearch}
          exportToExcel={exportToExcel}
          C={C}
          btnG={btnG}
          tbl={tbl}
          tblH={tblH}
          tblC={tblC}
          badge={badge}
        />
      )}

      {['move', 'tools', 'inventory'].includes(warehouseTab) && (
        <WarehouseOperationsPanel
          isMobile={isMobile}
          warehouseTab={warehouseTab}
          C={C}
          card={card}
          inp={inp}
          btnO={btnO}
          btnG={btnG}
          btnB={btnB}
          btnGr={btnGr}
          btnR={btnR}
          badge={badge}
          tbl={tbl}
          tblH={tblH}
          tblC={tblC}
          showForm={showForm}
          setShowForm={setShowForm}
          projects={projects}
          visibleActiveProjects={visibleActiveProjects}
          warehouseMain={warehouseMain}
          materials={materials}
          warehouseMovements={warehouseMovements}
          newMovement={newMovement}
          setNewMovement={setNewMovement}
          applyWarehouseMovement={applyWarehouseMovement}
          buildMovementDoc={buildMovementDoc}
          showPreview={showPreview}
          toolsTab={toolsTab}
          setToolsTab={setToolsTab}
          editingItem={editingItem}
          setEditingItem={setEditingItem}
          newTool={newTool}
          setNewTool={setNewTool}
          saveTool={saveTool}
          deleteTool={deleteTool}
          tools={tools}
          toolHistory={toolHistory}
          isProrab={isProrab}
          setShowIssueToolModal={setShowIssueToolModal}
          setShowReturnToolModal={setShowReturnToolModal}
          TOOL_STATUSES={TOOL_STATUSES}
          newInventory={newInventory}
          setNewInventory={setNewInventory}
          selectedInventory={selectedInventory}
          setSelectedInventory={setSelectedInventory}
          inventory={inventory}
          buildInventoryDoc={buildInventoryDoc}
          refreshData={refreshData}
          user={user}
        />
      )}
    </div>
  );
}
