import {
  buildM8ReportContent,
  buildM29ReportContent,
  buildMaterialRequirementReportContent,
} from './materialDocumentUtils';
import {
  buildAOSKDocContent,
  buildExecPackageDocContent,
  buildIGDDocContent,
  buildKS11DocContent,
  buildKS14DocContent,
  buildM2DocContent,
  buildM15DocContent,
  buildSpecJournalDocContent,
  buildSupervisorMonthlyReportDocContent,
  buildSupplementaryAgreementDocContent,
  buildVATBookDocContent,
} from './printDocumentBuilders';

export const createPrintDocContext = ({
  companyRequisites,
  companyName,
  projects,
  hiddenActs,
  workJournal,
  projectPlanDone,
  materialInspections,
  cableJournal,
  tbJournal,
  prescriptionsList,
  supplierInvoices,
  interimActs,
  supervisorActs,
  user,
}) => () => ({
  companyRequisites,
  companyName,
  projects,
  hiddenActs,
  workJournal,
  projectPlanDone,
  materialInspections,
  cableJournal,
  tbJournal,
  prescriptionsList,
  supplierInvoices,
  interimActs,
  supervisorActs,
  user,
});

export const createAppPrintBuilders = ({
  printDocContext,
  projects,
  materialTransfers,
  activeEstimatesForProject,
  materialReconciliationRows,
  estimateWorkNormRequirementRows,
  materialNormControlSummaryForProject,
  workJournal,
}) => ({
  buildM15Content: (transfer) => buildM15DocContent(transfer, printDocContext()),
  buildAOSKContent: (projectName) => buildAOSKDocContent(projectName, printDocContext()),
  buildKS11Content: (project) => buildKS11DocContent(project, printDocContext()),
  buildKS14Content: (project) => buildKS14DocContent(project, printDocContext()),
  buildIGDContent: (projectName) => buildIGDDocContent(projectName, printDocContext()),
  buildSpecJournalContent: (projectName, kind) => buildSpecJournalDocContent(projectName, kind, printDocContext()),
  buildM2Content: (supplier, items, projectName, recipientName, recipientPassport) =>
    buildM2DocContent(supplier, items, projectName, recipientName, recipientPassport, printDocContext()),
  buildM8Content: (projectName, masterName, periodFrom, periodTo) => buildM8ReportContent({
    projectName,
    masterName,
    periodFrom,
    periodTo,
    projects,
    materialTransfers,
    activeEstimatesForProject,
    printDocContext: printDocContext(),
  }),
  buildMaterialRequirementContent: (projectName) => buildMaterialRequirementReportContent({
    projectName,
    projects,
    activeEstimatesForProject,
    materialReconciliationRows,
    estimateWorkNormRequirementRows,
    materialNormControlSummaryForProject,
    printDocContext: printDocContext(),
  }),
  buildVATBookContent: (periodFrom, periodTo) => buildVATBookDocContent(periodFrom, periodTo, printDocContext()),
  buildSupplementaryAgreementContent: (unx, project) => buildSupplementaryAgreementDocContent(unx, project, printDocContext()),
  buildExecPackageContent: (project) => buildExecPackageDocContent(project, printDocContext()),
  buildM29Content: (projectName, periodFrom, periodTo) => buildM29ReportContent({
    projectName,
    periodFrom,
    periodTo,
    projects,
    materialTransfers,
    workJournal,
    activeEstimatesForProject,
    printDocContext: printDocContext(),
  }),
  buildSupervisorMonthlyReport: (projectName, periodFrom, periodTo) =>
    buildSupervisorMonthlyReportDocContent(projectName, periodFrom, periodTo, printDocContext()),
});
