export const materialLookupText = (name) => String(name || '').toLowerCase().replace(/[.,;:()«»"']/g, ' ').replace(/\s+/g, ' ').trim();

const MATERIAL_MATCH_STOPWORDS = new Set([
  'гост', 'ту', 'сорт', 'марка', 'тип', 'вид', 'цвет', 'размер', 'разм',
  'мм', 'см', 'м', 'шт', 'кг', 'л', 'т', 'для', 'при', 'под', 'над', 'без',
  'основная', 'объект', 'материал', 'материалы', 'позиция', 'работы', 'работа',
  'комплект', 'комплекта', 'комплектов', 'изделие', 'изделия', 'серия',
]);

const materialMatchTokens = (name) => {
  const tokens = new Set();
  const add = (...values) => values.forEach(value => tokens.add(value));
  materialLookupText(name).split(' ').forEach(raw => {
    const token = raw.trim();
    if (token.length < 2 || MATERIAL_MATCH_STOPWORDS.has(token)) return;
    if (/^\d$/.test(token)) return;
    if (/^\d{4,}$/.test(token) && /^(13|20)/.test(token)) return;
    if (token.startsWith('керамогран')) add('керамогранит', 'гранит', 'керамическ');
    else if (token.startsWith('livorno') || token.startsWith('ливорн')) add('livorno', 'керамогранит', 'плитка');
    else if (token.startsWith('axima') || token.startsWith('аксима')) add('axima', 'керамогранит', 'плитка');
    else if (token.startsWith('керамич')) tokens.add('керамическ');
    else if (token.startsWith('гранит')) tokens.add('гранит');
    else if (token.startsWith('металлочереп') || token.startsWith('черепиц')) add('металлочерепица', 'черепица', 'кровля');
    else if (token.startsWith('монтер') || token.startsWith('monter')) add('монтеррей', 'металлочерепица', 'черепица', 'кровля');
    else if (token.startsWith('гкл') || token.startsWith('гипсокарт')) add('гкл', 'гипсокартон');
    else if (token.startsWith('гвл') || token.startsWith('гипсовол')) add('гвл', 'гипсоволокно');
    else if (token.includes('цемент')) tokens.add('цемент');
    else if (token.startsWith('смес')) tokens.add('смесь');
    else if (token.startsWith('ротб')) add('ротбанд', 'штукатурка', 'смесь');
    else if (token.startsWith('хабез')) add('хабез', 'штукатурка', 'смесь');
    else if (token.startsWith('старт')) add('старт', 'штукатурка', 'шпатлевка', 'смесь');
    else if (token.startsWith('кнауф') || token.startsWith('knauf')) tokens.add('кнауф');
    else if (token.startsWith('песк')) tokens.add('песок');
    else if (token.startsWith('бетон')) tokens.add('бетон');
    else if (token.startsWith('глаз')) tokens.add('глазур');
    else if (token.startsWith('матов') || token.startsWith('неполир')) tokens.add('матов');
    else if (token.startsWith('полир')) tokens.add('полир');
    else if (token.startsWith('плит')) tokens.add('плитка');
    else if (token.startsWith('кле')) tokens.add('клей');
    else if (token.startsWith('грунт')) tokens.add('грунтовка');
    else if (token.startsWith('штукатур')) tokens.add('штукатурка');
    else if (token.startsWith('шпатлев') || token.startsWith('шпаклев')) tokens.add('шпатлевка');
    else if (token.startsWith('профил')) tokens.add('профиль');
    else if (token.startsWith('угол')) tokens.add('уголок');
    else if (token.startsWith('подвес')) tokens.add('подвес');
    else if (token.startsWith('маяк') || token.startsWith('маяч')) tokens.add('маяк');
    else if (token.startsWith('рейк')) tokens.add('рейка');
    else if (token.startsWith('лент')) tokens.add('лента');
    else if (token.startsWith('серпян')) tokens.add('серпянка');
    else if (token.startsWith('саморез') || token.startsWith('шуруп')) tokens.add('саморез');
    else if (token.startsWith('анкер')) tokens.add('анкер');
    else if (token.startsWith('болт')) tokens.add('болт');
    else if (token.startsWith('гайк')) tokens.add('гайка');
    else if (token.startsWith('шайб')) tokens.add('шайба');
    else if (token.startsWith('кабел')) tokens.add('кабель');
    else if (token.startsWith('провод')) tokens.add('провод');
    else if (token.startsWith('светиль') || token.startsWith('табло')) tokens.add('светильник');
    else if (token.startsWith('ламп')) tokens.add('лампа');
    else if (token.startsWith('розет')) tokens.add('розетка');
    else if (token.startsWith('выключ')) tokens.add('выключатель');
    else if (token.startsWith('втул')) tokens.add('втулка');
    else if (token.startsWith('хомут')) tokens.add('хомут');
    else if (token.startsWith('скоб')) tokens.add('скоба');
    else if (token.startsWith('труб')) tokens.add('труба');
    else if (token.startsWith('радиатор')) tokens.add('радиатор');
    else if (token.startsWith('фитинг')) tokens.add('фитинг');
    else if (token.startsWith('муфт')) tokens.add('муфта');
    else if (token.startsWith('клапан')) tokens.add('клапан');
    else if (token.startsWith('американ')) tokens.add('американка');
    else if (token.startsWith('воздухоотв')) tokens.add('воздухоотводчик');
    else if (token.startsWith('кран')) tokens.add('кран');
    else if (token.startsWith('креп')) tokens.add('крепеж');
    else if (token.startsWith('скреп')) tokens.add('скрепа');
    else if (token.startsWith('дюб')) tokens.add('дюбель');
    else if (token.startsWith('клин')) tokens.add('клин');
    else if (token.startsWith('кроншт')) tokens.add('кронштейн');
    else if (token.startsWith('направл')) tokens.add('направляющая');
    else if (token.startsWith('доск')) tokens.add('доска');
    else if (token.startsWith('брус')) tokens.add('брус');
    else if (token.startsWith('фанер')) tokens.add('фанера');
    else if (token.startsWith('осп') || token.startsWith('osb')) tokens.add('осп');
    else if (token.startsWith('армат')) tokens.add('арматура');
    else if (token.startsWith('гвозд')) tokens.add('гвоздь');
    else if (token.startsWith('шпил')) tokens.add('шпилька');
    else if (token.startsWith('перф')) tokens.add('перфолента');
    else if (token.startsWith('краск') || token.startsWith('окрас')) tokens.add('краска');
    else if (token.startsWith('эмал')) tokens.add('эмаль');
    else if (token.startsWith('лак')) tokens.add('лак');
    else if (token.startsWith('гермет')) tokens.add('герметик');
    else if (token.startsWith('силикон')) tokens.add('силикон');
    else if (token.startsWith('пен')) tokens.add('пена');
    else if (token.startsWith('раствор')) tokens.add('раствор');
    else if (token.startsWith('алебастр')) tokens.add('алебастр');
    else if (token.startsWith('гипс')) tokens.add('гипс');
    else if (token.startsWith('извест')) tokens.add('известь');
    else tokens.add(token);
  });
  return tokens;
};

const materialFamilyTags = (tokens) => {
  const t = new Set(tokens || []);
  const families = new Set();
  if (t.has('клей')) families.add('adhesive');
  if (t.has('штукатурка') || t.has('ротбанд') || (t.has('смесь') && (t.has('хабез') || t.has('старт')))) families.add('plaster');
  if (t.has('шпатлевка') && !t.has('штукатурка')) families.add('putty');
  if (t.has('грунтовка')) families.add('primer');
  if (t.has('цемент') && !['plaster', 'putty', 'adhesive'].some(f => families.has(f))) families.add('cement');
  if (t.has('бетон')) families.add('concrete');
  if (t.has('песок')) families.add('sand');
  if (!t.has('клей') && ['керамогранит', 'плитка', 'гранит', 'керамическ'].some(x => t.has(x))) families.add('tile');
  if (t.has('гкл') || t.has('гипсокартон')) families.add('gkl');
  if (t.has('гвл') || t.has('гипсоволокно')) families.add('gvl');
  if (['профиль', 'уголок', 'подвес', 'маяк', 'рейка', 'направляющая'].some(x => t.has(x))) families.add('metal_profile');
  if (['саморез', 'анкер', 'болт', 'гайка', 'шайба', 'дюбель', 'крепеж', 'гвоздь', 'шпилька', 'скрепа'].some(x => t.has(x))) families.add('fastener');
  if (t.has('кабель') || t.has('провод')) families.add('cable');
  if (['труба', 'фитинг', 'муфта', 'клапан', 'американка', 'хомут', 'кран'].some(x => t.has(x))) families.add('pipe');
  if (t.has('светильник') || t.has('лампа')) families.add('light');
  if (t.has('розетка') || t.has('выключатель')) families.add('electrical_device');
  if (['радиатор', 'кронштейн', 'воздухоотводчик'].some(x => t.has(x))) families.add('heating');
  if (['металлочерепица', 'черепица', 'кровля', 'монтеррей'].some(x => t.has(x))) families.add('roofing');
  if (['доска', 'брус', 'фанера', 'осп'].some(x => t.has(x))) families.add('wood_sheet');
  if (t.has('арматура')) families.add('rebar');
  if (['краска', 'эмаль', 'лак'].some(x => t.has(x))) families.add('paint');
  if (['герметик', 'силикон', 'пена'].some(x => t.has(x))) families.add('sealant');
  if (['раствор', 'алебастр', 'гипс', 'известь'].some(x => t.has(x)) && !families.has('plaster') && !families.has('putty')) families.add('binder_mix');
  return families;
};

const materialSetIntersection = (left, right) => new Set([...left].filter(x => right.has(x)));

export const materialNameMatchScore = (left, right) => {
  const leftKey = materialLookupText(left);
  const rightKey = materialLookupText(right);
  if (!leftKey || !rightKey) return 0;
  if (leftKey === rightKey) return 1;
  if (leftKey.length >= 10 && rightKey.length >= 10 && (leftKey.includes(rightKey) || rightKey.includes(leftKey))) return 0.92;
  const leftTokens = materialMatchTokens(leftKey);
  const rightTokens = materialMatchTokens(rightKey);
  if (!leftTokens.size || !rightTokens.size) return 0;
  const common = materialSetIntersection(leftTokens, rightTokens);
  const commonFamilies = materialSetIntersection(materialFamilyTags(leftTokens), materialFamilyTags(rightTokens));
  const familyScore = commonFamilies.size ? (['tile', 'plaster', 'putty', 'primer', 'cement', 'gkl', 'gvl', 'metal_profile', 'fastener', 'cable', 'pipe', 'roofing', 'paint', 'sealant', 'adhesive'].some(f => commonFamilies.has(f)) ? 0.82 : 0.76) : 0;
  if (!common.size) return familyScore;
  if ((leftTokens.has('металлочерепица') || leftTokens.has('черепица')) && (rightTokens.has('металлочерепица') || rightTokens.has('черепица'))) return 0.84;
  if (['керамогранит', 'плитка'].some(x => leftTokens.has(x)) && ['керамогранит', 'плитка'].some(x => rightTokens.has(x)) && ['livorno', 'axima', 'гранит', 'керамическ', 'матов', 'глазур'].some(x => common.has(x))) return 0.86;
  if (['ротбанд', 'кнауф', 'смесь', 'хабез', 'старт'].some(x => leftTokens.has(x)) && ['ротбанд', 'кнауф', 'смесь', 'хабез', 'старт'].some(x => rightTokens.has(x)) && ['штукатурка', 'шпатлевка', 'смесь', 'ротбанд', 'кнауф'].some(x => common.has(x))) return 0.84;
  if (common.has('гранит') && common.has('керамическ')) return 0.86;
  if (['гкл', 'гипсокартон'].some(x => leftTokens.has(x)) && ['гкл', 'гипсокартон'].some(x => rightTokens.has(x))) return 0.84;
  if (['гвл', 'гипсоволокно'].some(x => leftTokens.has(x)) && ['гвл', 'гипсоволокно'].some(x => rightTokens.has(x))) return 0.84;
  if (familyScore) return Math.max(familyScore, 0.78);
  const score = common.size / Math.max(1, Math.min(leftTokens.size, rightTokens.size));
  const longCommon = [...common].filter(t => t.length >= 6);
  const strongCommon = materialSetIntersection(common, new Set(['цемент', 'бетон', 'песок', 'саморез', 'анкер', 'болт', 'гайка', 'шайба', 'кабель', 'провод', 'труба', 'радиатор', 'кран', 'клей', 'плитка', 'керамогранит', 'гранит', 'керамическ']));
  if (strongCommon.size && common.size >= 2) return Math.min(0.82, Math.max(score + 0.2, 0.62));
  if (common.size >= 3 && score >= 0.45) return Math.min(0.9, score + 0.15);
  if (common.size >= 2 && longCommon.length && score >= 0.4) return Math.min(0.82, score + 0.1);
  if (longCommon.length && score >= 0.65) return Math.min(0.72, score);
  return score >= 0.7 ? score : 0;
};

export const materialAutoMatchSafe = (left, right, score) => {
  const leftKey = materialLookupText(left);
  const rightKey = materialLookupText(right);
  if (leftKey && rightKey && leftKey === rightKey) return true;
  if (leftKey.length >= 10 && rightKey.length >= 10 && (leftKey.includes(rightKey) || rightKey.includes(leftKey))) return true;
  const leftTokens = materialMatchTokens(left);
  const rightTokens = materialMatchTokens(right);
  const common = materialSetIntersection(leftTokens, rightTokens);
  const commonFamilies = materialSetIntersection(materialFamilyTags(leftTokens), materialFamilyTags(rightTokens));
  if (score >= 0.86 && (common.size >= 2 || commonFamilies.size > 0)) return true;
  const broadSafeFamilies = new Set(['tile', 'plaster', 'putty', 'primer', 'gkl', 'gvl', 'metal_profile', 'fastener', 'roofing', 'wood_sheet', 'rebar', 'sealant', 'binder_mix']);
  if (score >= 0.84 && common.size >= 1 && [...commonFamilies].some(f => broadSafeFamilies.has(f))) return true;
  if (score >= 0.82 && common.size >= 2) return true;
  return false;
};
