export const emptySupplierForm = () => ({
  name: '',
  phone: '',
  email: '',
  specialization: '',
  category: 'Сыпучие и бетон',
  rating: 5.0,
  status: 'Активный',
  inn: '',
  kpp: '',
  ogrn: '',
  legalAddress: '',
  actualAddress: '',
  bank: '',
  bik: '',
  account: '',
  korAccount: '',
  directorName: '',
  directorPosition: '',
  contractUrl: '',
  contractNumber: '',
  contractDate: '',
  licenseUrl: '',
  priceUrl: '',
  website: '',
  notes: '',
});

export const normalizeSupplierPayload = (supplier = {}) => ({
  ...emptySupplierForm(),
  ...supplier,
  legalAddress: supplier.legalAddress || supplier.legal_address || '',
  actualAddress: supplier.actualAddress || supplier.actual_address || '',
  korAccount: supplier.korAccount || supplier.kor_account || '',
  directorName: supplier.directorName || supplier.director_name || '',
  directorPosition: supplier.directorPosition || supplier.director_position || '',
  contractUrl: supplier.contractUrl || supplier.contract_url || '',
  contractNumber: supplier.contractNumber || supplier.contract_number || '',
  contractDate: String(supplier.contractDate || supplier.contract_date || '').slice(0, 10),
  licenseUrl: supplier.licenseUrl || supplier.license_url || '',
  priceUrl: supplier.priceUrl || supplier.price_url || '',
});
